// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	restmodels "webank/DI/restapi/api_v1/restmodels"
)

// GetJobLogByLineOKCode is the HTTP code returned for type GetJobLogByLineOK
const GetJobLogByLineOKCode int = 200

/*GetJobLogByLineOK OK

swagger:response getJobLogByLineOK
*/
type GetJobLogByLineOK struct {

	/*
	  In: Body
	*/
	Payload *restmodels.LogResponse `json:"body,omitempty"`
}

// NewGetJobLogByLineOK creates GetJobLogByLineOK with default headers values
func NewGetJobLogByLineOK() *GetJobLogByLineOK {

	return &GetJobLogByLineOK{}
}

// WithPayload adds the payload to the get job log by line o k response
func (o *GetJobLogByLineOK) WithPayload(payload *restmodels.LogResponse) *GetJobLogByLineOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get job log by line o k response
func (o *GetJobLogByLineOK) SetPayload(payload *restmodels.LogResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobLogByLineOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJobLogByLineUnauthorizedCode is the HTTP code returned for type GetJobLogByLineUnauthorized
const GetJobLogByLineUnauthorizedCode int = 401

/*GetJobLogByLineUnauthorized Unauthorized

swagger:response getJobLogByLineUnauthorized
*/
type GetJobLogByLineUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetJobLogByLineUnauthorized creates GetJobLogByLineUnauthorized with default headers values
func NewGetJobLogByLineUnauthorized() *GetJobLogByLineUnauthorized {

	return &GetJobLogByLineUnauthorized{}
}

// WithPayload adds the payload to the get job log by line unauthorized response
func (o *GetJobLogByLineUnauthorized) WithPayload(payload *restmodels.Error) *GetJobLogByLineUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get job log by line unauthorized response
func (o *GetJobLogByLineUnauthorized) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobLogByLineUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJobLogByLineNotFoundCode is the HTTP code returned for type GetJobLogByLineNotFound
const GetJobLogByLineNotFoundCode int = 404

/*GetJobLogByLineNotFound Model create failed

swagger:response getJobLogByLineNotFound
*/
type GetJobLogByLineNotFound struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetJobLogByLineNotFound creates GetJobLogByLineNotFound with default headers values
func NewGetJobLogByLineNotFound() *GetJobLogByLineNotFound {

	return &GetJobLogByLineNotFound{}
}

// WithPayload adds the payload to the get job log by line not found response
func (o *GetJobLogByLineNotFound) WithPayload(payload *restmodels.Error) *GetJobLogByLineNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get job log by line not found response
func (o *GetJobLogByLineNotFound) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobLogByLineNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
