// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListReportVersionsByReportIDParams creates a new ListReportVersionsByReportIDParams object
// no default values defined in spec.
func NewListReportVersionsByReportIDParams() ListReportVersionsByReportIDParams {

	return ListReportVersionsByReportIDParams{}
}

// ListReportVersionsByReportIDParams contains all the bound params for the list report versions by report Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters listReportVersionsByReportId
type ListReportVersionsByReportIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ReportID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListReportVersionsByReportIDParams() beforehand.
func (o *ListReportVersionsByReportIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rReportID, rhkReportID, _ := route.Params.GetOK("reportId")
	if err := o.bindReportID(rReportID, rhkReportID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindReportID binds and validates parameter ReportID from path.
func (o *ListReportVersionsByReportIDParams) bindReportID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("reportId", "path", "int64", raw)
	}
	o.ReportID = value

	return nil
}
