apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controlcenter-gateway-deployment
  namespace: {{.Values.namespace}}
  labels:
    app: controlcenter-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlcenter-gateway
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: controlcenter-gateway
    spec:
      #serviceAccountName: cc-go-sa
      containers:
      - name: cc-gateway
        image: {{.Values.ccGateway.image.repository}}:{{.Values.ccGateway.image.tag}}
        imagePullPolicy: {{.Values.ccGateway.image.pullPolicy}}
        ports:
        - containerPort: 8081
        command:
          - /apigateway/mlss-apigateway
          - -conf
          - /caddy-config/Caddyfile
        volumeMounts:
        - name: config-volume
          mountPath: /caddy-config
        - name: timezone-volume
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: hubsecret
      volumes:
      - name: config-volume
        configMap:
          name: cc-gateway-config
          items:
          - key: Caddyfile
            path: Caddyfile
          - key: application-yml
            path: application.yml
          - key: server.crt
            path: server.crt
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      nodeSelector:
        {{range $key,$val := .Values.platformNodeSelectors}}
          {{$key}}: {{$val}}
        {{end}}
