apiVersion: v1
kind: Service
metadata:
  name: controlcenter-go
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: controlcenter-go
  type: NodePort
  ports:
  - protocol: TCP
    port: 6666
    targetPort: 6666
    nodePort: 30801
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
