// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "mlss-controlcenter-go/pkg/models"
)

// NewAddRoleParams creates a new AddRoleParams object
// no default values defined in spec.
func NewAddRoleParams() AddRoleParams {

	return AddRoleParams{}
}

// AddRoleParams contains all the bound params for the add role operation
// typically these are obtained from a http.Request
//
// swagger:parameters AddRole
type AddRoleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The role Request
	  Required: true
	  In: body
	*/
	Role *models.Role
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddRoleParams() beforehand.
func (o *AddRoleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Role
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("role", "body"))
			} else {
				res = append(res, errors.NewParseError("role", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Role = &body
			}
		}
	} else {
		res = append(res, errors.Required("role", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
