// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddRoleHandlerFunc turns a function with the right signature into a add role handler
type AddRoleHandlerFunc func(AddRoleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddRoleHandlerFunc) Handle(params AddRoleParams) middleware.Responder {
	return fn(params)
}

// AddRoleHandler interface for that can handle valid add role params
type AddRoleHandler interface {
	Handle(AddRoleParams) middleware.Responder
}

// NewAddRole creates a new http.Handler for the add role operation
func NewAddRole(ctx *middleware.Context, handler AddRoleHandler) *AddRole {
	return &AddRole{Context: ctx, Handler: handler}
}

/*AddRole swagger:route POST /cc/v1/roles Roles addRole

add role to db.

Optional extended description in Markdown.

*/
type AddRole struct {
	Context *middleware.Context
	Handler AddRoleHandler
}

func (o *AddRole) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddRoleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
