{{- if .Values.ingress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-horovod
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: {{ template "horovod.name" . }}
    chart: {{ template "horovod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: tensorboard
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Release.Name }}-horovod
            backend:
              serviceName: {{ template "horovod.fullname" . }}-tensorboard
              servicePort: 6006
{{- end }}
