apiVersion: v1
kind: Service
metadata:
  name: {{ template "horovod.fullname" . }}-master
  labels:
    app: {{ template "horovod.name" . }}
    chart: {{ template "horovod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: ssh 
    port: {{ .Values.sshPort }}
    targetPort: {{ .Values.sshPort }}
  selector:
    app: {{ template "horovod.name" . }}
    release: {{ .Release.Name }}
    role: mpimaster