// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelsResponse models response
// swagger:model ModelsResponse
type ModelsResponse struct {

	// model versions
	ModelVersions []*Model `json:"modelVersions"`

	// page number
	PageNumber int64 `json:"page_number,omitempty"`

	// page size
	PageSize int64 `json:"page_size,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`

	// total page
	TotalPage int64 `json:"total_page,omitempty"`
}

// Validate validates this models response
func (m *ModelsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateModelVersions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsResponse) validateModelVersions(formats strfmt.Registry) error {

	if swag.IsZero(m.ModelVersions) { // not required
		return nil
	}

	for i := 0; i < len(m.ModelVersions); i++ {
		if swag.IsZero(m.ModelVersions[i]) { // not required
			continue
		}

		if m.ModelVersions[i] != nil {
			if err := m.ModelVersions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("modelVersions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsResponse) UnmarshalBinary(b []byte) error {
	var res ModelsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
