// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ModelVersionPushEventResp model version push event resp
// swagger:model ModelVersionPushEventResp
type ModelVersionPushEventResp struct {

	// events
	Events []*ModelVersionPushEventRespBase `json:"events"`

	// model
	Model *ModelBase `json:"model,omitempty"`

	// model version
	ModelVersion *ModelVersionBase `json:"model_version,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this model version push event resp
func (m *ModelVersionPushEventResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvents(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModelVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelVersionPushEventResp) validateEvents(formats strfmt.Registry) error {

	if swag.IsZero(m.Events) { // not required
		return nil
	}

	for i := 0; i < len(m.Events); i++ {
		if swag.IsZero(m.Events[i]) { // not required
			continue
		}

		if m.Events[i] != nil {
			if err := m.Events[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("events" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ModelVersionPushEventResp) validateModel(formats strfmt.Registry) error {

	if swag.IsZero(m.Model) { // not required
		return nil
	}

	if m.Model != nil {
		if err := m.Model.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("model")
			}
			return err
		}
	}

	return nil
}

func (m *ModelVersionPushEventResp) validateModelVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.ModelVersion) { // not required
		return nil
	}

	if m.ModelVersion != nil {
		if err := m.ModelVersion.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("model_version")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelVersionPushEventResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelVersionPushEventResp) UnmarshalBinary(b []byte) error {
	var res ModelVersionPushEventResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
