// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// RemoveNodeLabelOKCode is the HTTP code returned for type RemoveNodeLabelOK
const RemoveNodeLabelOKCode int = 200

/*RemoveNodeLabelOK Detailed Role and Role information.

swagger:response removeNodeLabelOK
*/
type RemoveNodeLabelOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewRemoveNodeLabelOK creates RemoveNodeLabelOK with default headers values
func NewRemoveNodeLabelOK() *RemoveNodeLabelOK {

	return &RemoveNodeLabelOK{}
}

// WithPayload adds the payload to the remove node label o k response
func (o *RemoveNodeLabelOK) WithPayload(payload *models.Result) *RemoveNodeLabelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove node label o k response
func (o *RemoveNodeLabelOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveNodeLabelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RemoveNodeLabelUnauthorizedCode is the HTTP code returned for type RemoveNodeLabelUnauthorized
const RemoveNodeLabelUnauthorizedCode int = 401

/*RemoveNodeLabelUnauthorized Unauthorized

swagger:response removeNodeLabelUnauthorized
*/
type RemoveNodeLabelUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRemoveNodeLabelUnauthorized creates RemoveNodeLabelUnauthorized with default headers values
func NewRemoveNodeLabelUnauthorized() *RemoveNodeLabelUnauthorized {

	return &RemoveNodeLabelUnauthorized{}
}

// WithPayload adds the payload to the remove node label unauthorized response
func (o *RemoveNodeLabelUnauthorized) WithPayload(payload *models.Error) *RemoveNodeLabelUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove node label unauthorized response
func (o *RemoveNodeLabelUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveNodeLabelUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RemoveNodeLabelNotFoundCode is the HTTP code returned for type RemoveNodeLabelNotFound
const RemoveNodeLabelNotFoundCode int = 404

/*RemoveNodeLabelNotFound url to add namespace not found.

swagger:response removeNodeLabelNotFound
*/
type RemoveNodeLabelNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRemoveNodeLabelNotFound creates RemoveNodeLabelNotFound with default headers values
func NewRemoveNodeLabelNotFound() *RemoveNodeLabelNotFound {

	return &RemoveNodeLabelNotFound{}
}

// WithPayload adds the payload to the remove node label not found response
func (o *RemoveNodeLabelNotFound) WithPayload(payload *models.Error) *RemoveNodeLabelNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove node label not found response
func (o *RemoveNodeLabelNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveNodeLabelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
