// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RemoveNodeLabelHandlerFunc turns a function with the right signature into a remove node label handler
type RemoveNodeLabelHandlerFunc func(RemoveNodeLabelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveNodeLabelHandlerFunc) Handle(params RemoveNodeLabelParams) middleware.Responder {
	return fn(params)
}

// RemoveNodeLabelHandler interface for that can handle valid remove node label params
type RemoveNodeLabelHandler interface {
	Handle(RemoveNodeLabelParams) middleware.Responder
}

// NewRemoveNodeLabel creates a new http.Handler for the remove node label operation
func NewRemoveNodeLabel(ctx *middleware.Context, handler RemoveNodeLabelHandler) *RemoveNodeLabel {
	return &RemoveNodeLabel{Context: ctx, Handler: handler}
}

/*RemoveNodeLabel swagger:route DELETE /cc/v1/nodes/{nodeName}/labels/{label} Resources removeNodeLabel

delete labels.

Optional extended description in Markdown.

*/
type RemoveNodeLabel struct {
	Context *middleware.Context
	Handler RemoveNodeLabelHandler
}

func (o *RemoveNodeLabel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveNodeLabelParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
