// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "mlss-controlcenter-go/pkg/models"
)

// NewSetNamespaceRQParams creates a new SetNamespaceRQParams object
// no default values defined in spec.
func NewSetNamespaceRQParams() SetNamespaceRQParams {

	return SetNamespaceRQParams{}
}

// SetNamespaceRQParams contains all the bound params for the set namespace r q operation
// typically these are obtained from a http.Request
//
// swagger:parameters SetNamespaceRQ
type SetNamespaceRQParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The namespace resourcesQuota Request
	  Required: true
	  In: body
	*/
	ResourcesQuota *models.ResourcesQuota
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSetNamespaceRQParams() beforehand.
func (o *SetNamespaceRQParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ResourcesQuota
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("resourcesQuota", "body"))
			} else {
				res = append(res, errors.NewParseError("resourcesQuota", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ResourcesQuota = &body
			}
		}
	} else {
		res = append(res, errors.Required("resourcesQuota", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
