// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SetNamespaceRQHandlerFunc turns a function with the right signature into a set namespace r q handler
type SetNamespaceRQHandlerFunc func(SetNamespaceRQParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SetNamespaceRQHandlerFunc) Handle(params SetNamespaceRQParams) middleware.Responder {
	return fn(params)
}

// SetNamespaceRQHandler interface for that can handle valid set namespace r q params
type SetNamespaceRQHandler interface {
	Handle(SetNamespaceRQParams) middleware.Responder
}

// NewSetNamespaceRQ creates a new http.Handler for the set namespace r q operation
func NewSetNamespaceRQ(ctx *middleware.Context, handler SetNamespaceRQHandler) *SetNamespaceRQ {
	return &SetNamespaceRQ{Context: ctx, Handler: handler}
}

/*SetNamespaceRQ swagger:route PUT /cc/v1/resources Resources setNamespaceRQ

update a namespace rq.

Optional extended description in Markdown.

*/
type SetNamespaceRQ struct {
	Context *middleware.Context
	Handler SetNamespaceRQHandler
}

func (o *SetNamespaceRQ) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetNamespaceRQParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
