// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "mlss-controlcenter-go/pkg/models"
)

// NewUpdateLabelsParams creates a new UpdateLabelsParams object
// no default values defined in spec.
func NewUpdateLabelsParams() UpdateLabelsParams {

	return UpdateLabelsParams{}
}

// UpdateLabelsParams contains all the bound params for the update labels operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateLabels
type UpdateLabelsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The namespace resourcesQuota Request
	  Required: true
	  In: body
	*/
	ResourcesQuota *models.LabelsRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateLabelsParams() beforehand.
func (o *UpdateLabelsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.LabelsRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("resourcesQuota", "body"))
			} else {
				res = append(res, errors.NewParseError("resourcesQuota", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ResourcesQuota = &body
			}
		}
	} else {
		res = append(res, errors.Required("resourcesQuota", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
