// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// UpdateLabelsOKCode is the HTTP code returned for type UpdateLabelsOK
const UpdateLabelsOKCode int = 200

/*UpdateLabelsOK Detailed namespace and namespace information.

swagger:response updateLabelsOK
*/
type UpdateLabelsOK struct {

	/*
	  In: Body
	*/
	Payload *models.LabelsResponse `json:"body,omitempty"`
}

// NewUpdateLabelsOK creates UpdateLabelsOK with default headers values
func NewUpdateLabelsOK() *UpdateLabelsOK {

	return &UpdateLabelsOK{}
}

// WithPayload adds the payload to the update labels o k response
func (o *UpdateLabelsOK) WithPayload(payload *models.LabelsResponse) *UpdateLabelsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update labels o k response
func (o *UpdateLabelsOK) SetPayload(payload *models.LabelsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateLabelsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateLabelsUnauthorizedCode is the HTTP code returned for type UpdateLabelsUnauthorized
const UpdateLabelsUnauthorizedCode int = 401

/*UpdateLabelsUnauthorized Unauthorized

swagger:response updateLabelsUnauthorized
*/
type UpdateLabelsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateLabelsUnauthorized creates UpdateLabelsUnauthorized with default headers values
func NewUpdateLabelsUnauthorized() *UpdateLabelsUnauthorized {

	return &UpdateLabelsUnauthorized{}
}

// WithPayload adds the payload to the update labels unauthorized response
func (o *UpdateLabelsUnauthorized) WithPayload(payload *models.Error) *UpdateLabelsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update labels unauthorized response
func (o *UpdateLabelsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateLabelsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateLabelsNotFoundCode is the HTTP code returned for type UpdateLabelsNotFound
const UpdateLabelsNotFoundCode int = 404

/*UpdateLabelsNotFound url to add namespace not found.

swagger:response updateLabelsNotFound
*/
type UpdateLabelsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateLabelsNotFound creates UpdateLabelsNotFound with default headers values
func NewUpdateLabelsNotFound() *UpdateLabelsNotFound {

	return &UpdateLabelsNotFound{}
}

// WithPayload adds the payload to the update labels not found response
func (o *UpdateLabelsNotFound) WithPayload(payload *models.Error) *UpdateLabelsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update labels not found response
func (o *UpdateLabelsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateLabelsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
