// Code generated by go-swagger; DO NOT EDIT.

package model_deploy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-mf/pkg/models"
)

// GetServiceOKCode is the HTTP code returned for type GetServiceOK
const GetServiceOKCode int = 200

/*GetServiceOK OK

swagger:response getServiceOK
*/
type GetServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetService `json:"body,omitempty"`
}

// NewGetServiceOK creates GetServiceOK with default headers values
func NewGetServiceOK() *GetServiceOK {

	return &GetServiceOK{}
}

// WithPayload adds the payload to the get service o k response
func (o *GetServiceOK) WithPayload(payload *models.GetService) *GetServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service o k response
func (o *GetServiceOK) SetPayload(payload *models.GetService) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetServiceUnauthorizedCode is the HTTP code returned for type GetServiceUnauthorized
const GetServiceUnauthorizedCode int = 401

/*GetServiceUnauthorized Unauthorized

swagger:response getServiceUnauthorized
*/
type GetServiceUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetServiceUnauthorized creates GetServiceUnauthorized with default headers values
func NewGetServiceUnauthorized() *GetServiceUnauthorized {

	return &GetServiceUnauthorized{}
}

// WithPayload adds the payload to the get service unauthorized response
func (o *GetServiceUnauthorized) WithPayload(payload *models.Error) *GetServiceUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service unauthorized response
func (o *GetServiceUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetServiceNotFoundCode is the HTTP code returned for type GetServiceNotFound
const GetServiceNotFoundCode int = 404

/*GetServiceNotFound Model create failed

swagger:response getServiceNotFound
*/
type GetServiceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetServiceNotFound creates GetServiceNotFound with default headers values
func NewGetServiceNotFound() *GetServiceNotFound {

	return &GetServiceNotFound{}
}

// WithPayload adds the payload to the get service not found response
func (o *GetServiceNotFound) WithPayload(payload *models.Error) *GetServiceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service not found response
func (o *GetServiceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
