apiVersion: v1
kind: Service
metadata:
  name: s3
  namespace: {{.Values.namespace}}
spec:
{{ if .Values.services.expose_node_port }}
  type: NodePort
{{ end }}
  selector:
    service: storage
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4572
    # newly added
{{ if .Values.services.expose_node_port }}
    nodePort: 30797
{{ end }}

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{.Values.namespace}}
  labels:
    component: elasticsearch
spec:
{{ if .Values.services.expose_node_port }}
  type: NodePort
{{ end }}
  selector:
    service: storage
  ports:
  - name: http
    port: 9200
    targetPort: 4571
    protocol: TCP
    # newly added
{{ if .Values.services.expose_node_port }}
    nodePort: 30880
{{ end }}

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: storage
  namespace: {{.Values.namespace}}
spec:
  serviceName: storage
  replicas: 1
  template:
    metadata:
      labels:
        service: storage
    spec:
      volumes:
        - name: localstack-pv-volume
          persistentVolumeClaim:
            claimName: localstack-pvc-{{.Values.namespace}}
        - name: timezone-volume
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: File
      containers:
        - name: storage
#          image: localstack/localstack:0.8.6
#          image: localstack_new:0.0.1
          image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}{{.Values.docker.image_prefix}}:localstack-latest
{{ if .Values.docker.pullPolicy }}
          imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
          env:
          - name: SERVICES
            value: s3,elasticsearch
          - name: DEBUG
            value: "1"
          - name: DATA_DIR
            value: "/tmp/localstack/data"
          ports:
          - containerPort: 4572
            protocol: TCP
          - containerPort: 4571
            protocol: TCP
          volumeMounts:
            - mountPath: "/tmp/localstack/data"
              name: localstack-pv-volume
            - name: timezone-volume
              mountPath: /etc/localtime
      imagePullSecrets:
      - name: hubsecret     
      nodeSelector:
        {{range $key,$val := .Values.platformNodeSelectors}}
          {{$key}}: {{$val}}
        {{end}}
