// Code generated by go-swagger; DO NOT EDIT.

package dss_user_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDssUserInfoHandlerFunc turns a function with the right signature into a get dss user info handler
type GetDssUserInfoHandlerFunc func(GetDssUserInfoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDssUserInfoHandlerFunc) Handle(params GetDssUserInfoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDssUserInfoHandler interface for that can handle valid get dss user info params
type GetDssUserInfoHandler interface {
	Handle(GetDssUserInfoParams, interface{}) middleware.Responder
}

// NewGetDssUserInfo creates a new http.Handler for the get dss user info operation
func NewGetDssUserInfo(ctx *middleware.Context, handler GetDssUserInfoHandler) *GetDssUserInfo {
	return &GetDssUserInfo{Context: ctx, Handler: handler}
}

/*GetDssUserInfo swagger:route GET /di/v1/dssUserInfo DssUserInfo getDssUserInfo

Get DSS UserInfo

Get DSS UserInfo

*/
type GetDssUserInfo struct {
	Context *middleware.Context
	Handler GetDssUserInfoHandler
}

func (o *GetDssUserInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDssUserInfoParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
