apiVersion: apps/v1
kind: Deployment
metadata:
  name: di-jm
  namespace: {{.Values.namespace}}
  labels:
    service: di-jm
    environment: {{.Values.env}}
spec:
  selector:
    matchLabels:
      service: di-jm
      environment: {{.Values.env}}
  replicas: 1
  template:
    metadata:
      labels:
        service: di-jm
        environment: {{.Values.env}}
        version:  {{.Values.lcm.version}}
    spec:
      volumes:
        - name: di-config
          configMap:
            name: di-config
        - name: ffdl-certs
          configMap:
            name: ffdl-certs
        - name: timezone-volume
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: File
      serviceAccount: lcm
      serviceAccountName: lcm
      containers:
      - name: jm
        image: {{.Values.server_repository}}:{{.Values.jm.version}}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/mlss/
          name: di-config
        - mountPath: /etc/ssl/dlaas/
          name: ffdl-certs
        - name: timezone-volume
          mountPath: /etc/localtime
        env:
        - name: DLAAS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_LEARNER_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_LOAD_TRAINING_DATA_MEM_IN_MB
          value: "300"
        - name: DLAAS_MILLI_CPU
          value: "60"
        - name: DLAAS_MEM_IN_MB
          value: "300"
        - name: DLAAS_DEVICE_PLUGIN
          value: "true"
        - name: DLAAS_IMAGE_TAG
          value: {{.Values.restapi.version}}
        - name: DLAAS_IMAGE_PULL_POLICY
          value: Always
        - name: DLAAS_ENV
          value: {{.Values.env}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: DLAAS_IMAGE_PREFIX
          value: 
        - name: DLAAS_LEARNER_TAG
          value: {{.Values.learner.tag}}
        - name: DLAAS_LEARNER_REGISTRY
          value: {{.Values.server_repository}}/webank/mlss-di
        - name: LINKIS_ADDRESS
          value: 127.0.0.1:8088
        - name: LINKIS_ADDRESS
          value: 127.0.0.1:8088
        - name: LINKIS_TOKEN_CODE
          value: MLSS
        - name: ENVIR
          value: {{.Values.envir}}
        - name: DLAAS_PUSH_METRICS_ENABLED
          value: "true"
        - name: DLAAS_MONGO_ADDRESS
          value: mongo.$(DLAAS_POD_NAMESPACE).svc.cluster.local
        - name: DLAAS_MONGO_USERNAME
          value: mlss
        - name: DLAAS_MONGO_PASSWORD
          value: mlss
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8443 /main"]
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
      imagePullSecrets:
      - name: hubsecret
      nodeSelector:
       {{range $key,$val := .Values.platformNodeSelectors}}
         {{$key}}: {{$val}}
       {{end}}

