apiVersion: v1
kind: Service
metadata:
  name: ffdl-lcm
  namespace: {{.Values.namespace}}
  labels:
    service: ffdl-lcm
    environment: {{.Values.envir}}
spec:
  ports:
  - name: grpc
    port: 80
    targetPort: 8080
  selector:
    service: ffdl-lcm
