apiVersion: v1
kind: Secret
metadata:
  name: lcm-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
  DLAAS_ETCD_ADDRESS: {{"http://etcd.prophecis.svc.cluster.local:2379"|b64enc}}
  DLAAS_ETCD_USERNAME: {{"test"|b64enc}}
  DLAAS_ETCD_PASSWORD: {{"test"|b64enc}}
  DLAAS_ETCD_PREFIX: {{"test"|b64enc}}
  DLAAS_LEARNER_TAG: {{"test"|b64enc}}
#### 1.4.1 #####
{{ if ne .Values.env "dev" }}
  DLAAS_MONGO_ADDRESS: {{"localhost:27017"|b64enc}}
  DLAAS_MONGO_USERNAME: {{"mlss"|b64enc}}
  DLAAS_MONGO_PASSWORD: {{"mlss"|b64enc}}
{{ end }}
  DLAAS_OBJECTSTORE_TYPE: {{"s3_datastore"|b64enc}}
  # auth_url needs to be the FQDN due to a limitation in the local S3 mock
  DLAAS_OBJECTSTORE_AUTH_URL: {{printf "minio-%s:9000" .Values.envir |b64enc}}
  DLAAS_OBJECTSTORE_USER_NAME: {{"AKIAIOSFODNN7EXAMPLE"|b64enc}}
  DLAAS_OBJECTSTORE_PASSWORD: {{"password"|b64enc}}
#################

######1.5.1######
  FLUENT_ELASTICSEARCH_HOST: {{"elasticsearch.prophecis.svc.cluster.local"|b64enc}}
  FLUENT_ELASTICSEARCH_PORT: {{"9200"|b64enc}}
  FLUENT_ELASTICSEARCH_USER: {{"test"|b64enc}}
  FLUENT_ELASTICSEARCH_PASSWD: {{"test"|b64enc}}
#################
