apiVersion:  apps/v1
kind: Deployment
metadata:
  name: ffdl-lcm
  namespace: {{.Values.namespace}}
  labels:
    service: ffdl-lcm
    environment: {{.Values.env}}
spec:
  selector:
    matchLabels:
      service: ffdl-lcm
      environment: {{.Values.env}}
  replicas: 1
  template:
    metadata:
      labels:
        service: ffdl-lcm
        environment: {{.Values.env}}
        version: {{.Values.lcm.version}}
    spec:
      volumes:
        - name: learner-kube
          secret:
            secretName: lcm-secrets
        - name: learner-config-volume
          configMap:
            name: learner-config
#        - name: static-volumes-config-volume
#          configMap:
#            name: static-volumes
#        - name: static-volumes-config-volume-v2
#          configMap:
#            name: static-volumes-v2
#        - name: etcd-ssl-cert
#          secret:
#            secretName: lcm-secrets
#            items: [{
#              key: DLAAS_ETCD_CERT,
#              path: etcd/etcd.cert
#            }]
######### 1.3.0  ###############
        - name: di-config
          configMap:
            name: di-config
################################
######### 1.4.0 ################
        - name: ffdl-certs
          configMap:
            name: ffdl-certs
        - name: timezone-volume
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: File
################################
######### 1.5.2 ################
        #- name: kube-config
          #hostPath:
            #path: /root/.kube
        #- name: helm-config
          #hostPath:
            #path: /root/.helm
        #- name: nfs-chart-volume
          #nfs:
            #server: 127.0.0.1
            #path: /data/nfs/charts
################################

      serviceAccount: lcm
      serviceAccountName: lcm
      containers:
      - name: ffdl-lcm-container
        image: {{.Values.server_repository}}:{{.Values.lcm.version}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/run/secrets/learner-kube
          name: learner-kube
        - mountPath: /etc/learner-config
          name: learner-config-volume
####### 1.3.0 ############
        - mountPath: /etc/mlss/
          name: di-config
##########################
####### 1.4.0 ############
        - mountPath: /etc/ssl/dlaas/
          name: ffdl-certs
        - name: timezone-volume
          mountPath: /etc/localtime
######### 1.5.2 ################
        #- name: kube-config
          #mountPath: /config/.kube/
        #- name: helm-config
          #mountpath: /config/.helm/
        #- name: nfs-chart-volume
          #mountPath: /tmp/charts
##########################
        env:
        - name: DLAAS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_LEARNER_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_SHARED_VOLUME_STORAGE_CLASS
          value: ""
        - name: DLAAS_LOAD_TRAINING_DATA_MEM_IN_MB
          value: "300"
        - name: DLAAS_MILLI_CPU
          value: "60"
        - name: DLAAS_MEM_IN_MB
          value: "300"
        - name: DLAAS_DEVICE_PLUGIN
          value: "true"
        - name: DLAAS_IMAGE_TAG
          value: {{.Values.restapi.version}}
        - name: DLAAS_IMAGE_PULL_POLICY
          value: Always
        - name: DLAAS_ENV
          value: {{.Values.env}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: DLAAS_IMAGE_PREFIX
          value: 
        - name: DLAAS_LEARNER_TAG
          value: {{.Values.learner.tag}}
        - name: DLAAS_LEARNER_REGISTRY
          value: {{.Values.server_repository}}/webank/mlss-di
        - name: LINKIS_ADDRESS
          value: 127.0.0.1:8088
        - name: LINKIS_TOKEN_CODE
          value: MLSS
        - name: ENVIR
          value: {{.Values.envir}}
        - name: FLUENT_BIT_LOG_PATH
          value: /mlss/di/jobs/
        - name: DLAAS_ETCD_ADDRESS
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_ADDRESS
        - name: DLAAS_ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_USERNAME
        - name: DLAAS_ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_PASSWORD
        - name: DLAAS_ETCD_PREFIX
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_ETCD_PREFIX
        - name: DLAAS_PUSH_METRICS_ENABLED
          value: "true"
        - name: DLAAS_MONGO_ADDRESS
          value: mongo.$(DLAAS_POD_NAMESPACE).svc.cluster.local
        - name: DLAAS_MONGO_USERNAME
          value: mlss
        - name: DLAAS_MONGO_PASSWORD
          value: mlss
        - name: DLAAS_OBJECTSTORE_TYPE
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_TYPE
        - name: DLAAS_OBJECTSTORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_AUTH_URL
        - name: DLAAS_OBJECTSTORE_USER_NAME
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_USER_NAME
        - name: DLAAS_OBJECTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: DLAAS_OBJECTSTORE_PASSWORD
##########
##1.5.1###
        - name: FLUENT_ELASTICSEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_HOST
        - name: FLUENT_ELASTICSEARCH_PORT
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_PORT
        - name: FLUENT_ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_USER
        - name: FLUENT_ELASTICSEARCH_PASSWD
          valueFrom:
            secretKeyRef:
              name: lcm-secrets
              key: FLUENT_ELASTICSEARCH_PASSWD
##########
##1.5.1###
        - name: HOME
          value: /config
##########
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8443 /main"]
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
      imagePullSecrets:
      - name: hubsecret
      nodeSelector:
       {{range $key,$val := .Values.platformNodeSelectors}}
         {{$key}}: {{$val}}
       {{end}}
