apiVersion: apps/v1
kind: Deployment
metadata:
  name: di-restapi
  namespace: {{.Values.namespace}}
  labels:
    service: di-restapi
    environment: {{.Values.env}}
spec:
  selector:
    matchLabels:
       service: di-restapi
       environment: {{.Values.env}}
  replicas: 1
  template:
    metadata:
      labels:
        service: di-restapi
        environment: {{.Values.env}}
        version: {{.Values.restapi.version}}
    spec:
######### 1.3.0 ############
      volumes:
      - name: di-config
        configMap:
          name: di-config
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      - name: oss-storage
        hostPath:
          path: /data/bdap-ss/mlss-data/tmp
          type: Directory
############################
      serviceAccount: lcm
      serviceAccountName: lcm
      containers:
      - name: di-restapi-container
        image: {{.Values.server_repository}}:{{.Values.restapi.version}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
####### 1.3.0 ############
        volumeMounts:
        - mountPath: /etc/mlss/
          name: di-config
        - name: timezone-volume
          mountPath: /etc/localtime
        - name: oss-storage
          mountPath: /data/oss-storage
##########################
        env:
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_ENV
          value: {{.Values.env}}
        - name: DLAAS_MONGO_ADDRESS
          value: mongo
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: DLAAS_MONGO_ADDRESS
          value: mongo:27017
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8080 /main"]
        #args: ["dlv --listen=:40000 --headless=true --api-version=2 exec /main -- --DLASS_PORT=8080"]
        resources:
          limits:
            cpu: 1000m
            memory: 3400Mi
        #livenessProbe:
        #  httpGet:
        #    path: /health
        #    port: 8080
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 10
      imagePullSecrets:
#      - name: regcred
      - name: hubsecret
      nodeSelector:
        {{range $key,$val := .Values.platformNodeSelectors}}
          {{$key}}: {{$val}}
        {{end}}
