apiVersion: v1
kind: Service
metadata:
  name: ffdl-restapi
  namespace: {{.Values.namespace}}
  labels:
    service: ffdl-restapi
    environment: {{.Values.envir}}
spec:
  type: NodePort
  ports:
  - name: ffdl
    port: 80
    targetPort: 8080
    nodePort: {{.Values.restapi.port}}
  - name: di-debug
    port: 30961
    targetPort: 30961
    nodePort: 30961
  selector:
    service: ffdl-restapi
