apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffdl-restapi
  namespace: {{.Values.namespace}}
  labels:
    service: ffdl-restapi
    environment: {{.Values.envir}}
spec:
  selector:
    matchLabels:
       service: ffdl-restapi
       environment: {{.Values.envir}}
  replicas: {{.Values.restapi.replicas}}
  template:
    metadata:
      labels:
        service: ffdl-restapi
        environment: {{.Values.envir}}
        version: {{.Values.restapi.version}}
    spec:
######### 1.3.0 ############
      volumes:
      - name: di-config
        configMap:
          name: di-config
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      - name: oss-storage
        hostPath:
          path: {{.Values.storage.share_storage_dir}}
          type: Directory
############################
      containers:
      - name: ffdl-restapi-container
        image: {{.Values.image.registry}}:{{.Values.restapi.version}}
{{ if .Values.image.pullPolicy }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
{{ end }}
        ports:
        - containerPort: 8080
####### 1.3.0 ############
        volumeMounts:
        - mountPath: /etc/mlss/
          name: di-config
        - name: timezone-volume
          mountPath: /etc/localtime
        - name: oss-storage
          mountPath: /data/oss-storage
##########################
        env:
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_ENV
          value: {{.Values.envir}}
        - name: MONGO_ADDRESS
          value: {{.Values.mongo.address}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: MONGO_ADDRESS
          value: {{.Values.mongo.address}}
        - name: MONGO_USERNAME
          value: {{.Values.mongo.username}}
        - name: MONGO_PASSWORD
          value: {{.Values.mongo.password}}
        - name: MONGO_DATABASE
          value: {{.Values.mongo.database}}
        - name: MONGO_Authentication_Database
          value: {{.Values.mongo.authenticationDatabase}}
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8080 /main"]
        #args: ["dlv --listen=:40004 --headless=true --api-version=2 exec /main -- --DLASS_PORT=8080"]
        resources:
          limits:
            cpu: {{.Values.restapi.cpus}}
            memory: {{.Values.restapi.memory}}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
      imagePullSecrets:
#      - name: regcred
      - name: hubsecret
      nodeSelector:
        {{range $key,$val := .Values.platformNodeSelectors}}
          {{$key}}: {{$val}}
        {{end}}
