apiVersion: apps/v1
kind: Deployment
metadata:
  name: di-storage
  namespace: {{.Values.namespace}}
  labels:
    environment: {{.Values.envir}}
    service: di-storage
spec:
  selector:
    matchLabels:
      service: di-storage
      environment: {{.Values.envir}}
  replicas: {{.Values.storage.replicas}}
  template:
    metadata:
      labels:
        service: di-storage
        environment: {{.Values.envir}}
        version: {{.Values.storage.version}}
    spec:
      volumes:
      - name: di-config
        configMap:
          name: di-config
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      - name: oss-storage
        hostPath:
          path: {{.Values.storage.share_storage_dir}}
          type: Directory
#      - name: ceph
#        hostPath:
#          path: {{.Values.ceph_path}}/
#      - name: bdap-ss
#        hostPath:
#          path: {{.Values.storage.dataPath}}{{.Values.storage.bdap_ss}}
#      - name: bdap-safess
#        hostPath:
#          path: {{.Values.storage.dataPath}}{{.Values.storage.bdap_safess}}
#      - name: bdapsafe-ss
#        hostPath:
#          path: {{.Values.storage.dataPath}}{{.Values.storage.bdapsafe_ss}}
      containers:
      - name: di-storage-rpc-server
        image: {{.Values.image.registry}}:{{.Values.storage.version}}
{{ if .Values.image.pullPolicy }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
{{ end }}
        ports:
        - containerPort: 8443
        env:
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_ENV
          value: {{.Values.envir}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: DLAAS_PUSH_METRICS_ENABLED
          value: "true"
        - name: LINKIS_ADDRESS
          value: {{.Values.linkis.address}}
        - name: LINKIS_TOKEN_CODE
          value: {{.Values.linkis.tokenCode}}
        - name: MONGO_ADDRESS
          value: {{.Values.mongo.address}}
        - name: MONGO_USERNAME
          value: {{.Values.mongo.username}}
        - name: MONGO_PASSWORD
          value: {{.Values.mongo.password}}
        - name: MONGO_DATABASE
          value: {{.Values.mongo.database}}
        - name: MONGO_Authentication_Database
          value: {{.Values.mongo.authenticationDatabase}}
        - name: DLAAS_OBJECTSTORE_TYPE
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_TYPE
        - name: DLAAS_OBJECTSTORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_AUTH_URL
        - name: DLAAS_OBJECTSTORE_USER_NAME
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_USER_NAME
        - name: DLAAS_OBJECTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_PASSWORD
        - name: DLAAS_ELASTICSEARCH_SCHEME
          value: {{.Values.elasticsearch.scheme}}
        - name: DLAAS_ELASTICSEARCH_ADDRESS
          value: {{.Values.elasticsearch.address}}
        - name: DLAAS_ELASTICSEARCH_ADDRESS
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_ADDRESS
        - name: DLAAS_ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_USERNAME
        - name: DLAAS_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_PASSWORD
        volumeMounts:
        - mountPath: /etc/mlss/
          name: di-config
        - name: timezone-volume
          mountPath: /etc/localtime
        - name: oss-storage
          mountPath: /data/oss-storage
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8443 /main"]
        resources:
          limits:
            cpu: {{.Values.storage.cpus}}
            memory: {{.Values.storage.memory}}
      imagePullSecrets:
      - name: hubsecret
      nodeSelector:
       {{range $key,$val := .Values.platformNodeSelectors}}
         {{$key}}: {{$val}}
       {{end}}

