apiVersion: v1
kind: Secret
metadata:
  name: trainingdata-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
  DLAAS_ELASTICSEARCH_ADDRESS: {{"http://elasticsearch.prophecis.svc.cluster.local:9200"|b64enc}}
  DLAAS_ELASTICSEARCH_USERNAME: {{"test"|b64enc}}
  DLAAS_ELASTICSEARCH_PASSWORD: {{"test"|b64enc}}
