apiVersion: v1
kind: Service
metadata:
  name: ffdl-trainingdata
  namespace: {{.Values.namespace}}
  labels:
    environment: {{.Values.envir}}
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 80
    targetPort: 8443
  selector:
    service: ffdl-trainingdata
