apiVersion: v1
kind: Secret
metadata:
  name: trainer-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:

{{ if ne .Values.env "dev" }}
  DLAAS_MONGO_ADDRESS: {{"localhost:27017"|b64enc}}
  DLAAS_MONGO_USERNAME: {{"mlss"|b64enc}}
  DLAAS_MONGO_PASSWORD: {{"mlss"|b64enc}}
{{ end }}
  DLAAS_OBJECTSTORE_TYPE: {{default "s3_datastore"|b64enc}}
  DLAAS_OBJECTSTORE_AUTH_URL: {{printf "minio-%s:9000" .Values.envir |b64enc}}
  DLAAS_OBJECTSTORE_USER_NAME: {{"AKIAIOSFODNN7EXAMPLE"|b64enc}}
  DLAAS_OBJECTSTORE_PASSWORD: {{"password"|b64enc}}
