apiVersion: v1
kind: Secret
metadata:
  name: storage-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
{{ if ne .Values.envir "dev" }}
  DLAAS_MONGO_ADDRESS: {{.Values.mongo.address|b64enc}}
  DLAAS_MONGO_USERNAME: {{.Values.mongo.username|b64enc}}
  DLAAS_MONGO_PASSWORD: {{.Values.mongo.password|b64enc}}
{{ end }}
  DLAAS_OBJECTSTORE_TYPE: {{.Values.objectstore.type|b64enc}}
  DLAAS_OBJECTSTORE_AUTH_URL: {{printf "minio-%s:9000" .Values.envir |b64enc}}
  DLAAS_OBJECTSTORE_USER_NAME: {{.Values.objectstore.username|b64enc}}
  DLAAS_OBJECTSTORE_PASSWORD: {{.Values.objectstore.password|b64enc}}

  DLAAS_ELASTICSEARCH_ADDRESS: {{.Values.elasticsearch.address|b64enc}}
  DLAAS_ELASTICSEARCH_USERNAME: {{.Values.elasticsearch.username|b64enc}}
  DLAAS_ELASTICSEARCH_PASSWORD: {{.Values.elasticsearch.password|b64enc}}
 # DLAAS_ELASTICSEARCH_CERT: {{.Values.elasticsearch.ssl_cert}} #cert has already been base64 encoded

