apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffdl-trainingdata
  namespace: {{.Values.namespace}}
  labels:
    environment: {{.Values.envir}}
    service: ffdl-trainingdata
spec:
  selector:
    matchLabels:
      service: ffdl-trainingdata
      environment: {{.Values.envir}}
  replicas: {{.Values.trainingdata.replicas}}
  template:
    metadata:
      labels:
        service: ffdl-trainingdata
        environment: {{.Values.envir}}
        version: {{.Values.trainingdata.version}}
    spec:
      containers:
      - name: ffdl-trainingdata-container
        image: {{.Values.image.registry}}:{{.Values.trainingdata.version}}
{{ if .Values.image.pullPolicy }}
        imagePullPolicy: {{.Values.image.pullPolicy}}
{{ end }}
        ports:
        - containerPort: 8443
        env:
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_ENV
          value: {{.Values.envir}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: DLAAS_ELASTICSEARCH_SCHEME
          value: {{.Values.elasticsearch.scheme}}
{{ if eq .Values.envir "dev" }}
        - name: DLAAS_ELASTICSEARCH_ADDRESS
          value: {{.Values.elasticsearch.address}}
{{ else }}
        - name: DLAAS_ELASTICSEARCH_ADDRESS
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_ADDRESS
        - name: DLAAS_ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_USERNAME
        - name: DLAAS_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_PASSWORD
{{ end }}
        volumeMounts:
####### 1.4.0 ############
        - mountPath: /etc/ssl/dlaas/
          name: ffdl-certs
        - name: timezone-volume
          mountPath: /etc/localtime
##########################
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8443 /main"]
        resources:
          limits:
            cpu: {{.Values.trainingdata.cpus}}
            memory: {{.Values.trainingdata.memory}}
######### 1.4.0 ################
      volumes:
      - name: ffdl-certs
        configMap:
          name: ffdl-certs
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
################################
      imagePullSecrets:
#      - name: regcred
       - name: hubsecret
#        livenessProbe:
#          exec:
#            command:
#              - /bin/sh
#              - -c
#              - "grpc-health-checker --port 8443 --tls"
#          initialDelaySeconds: 15
#          timeoutSeconds: 2
      nodeSelector:
        {{range $key,$val := .Values.platformNodeSelectors}}
          {{$key}}: {{$val}}
        {{end}}
