// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi jupyter-server
Jupyter Notebook Service


    Schemes:
      https
    Host: gateway.mlss.aide
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
