// Code generated by go-swagger; DO NOT EDIT.

package proxy_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddProxyUserHandlerFunc turns a function with the right signature into a add proxy user handler
type AddProxyUserHandlerFunc func(AddProxyUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddProxyUserHandlerFunc) Handle(params AddProxyUserParams) middleware.Responder {
	return fn(params)
}

// AddProxyUserHandler interface for that can handle valid add proxy user params
type AddProxyUserHandler interface {
	Handle(AddProxyUserParams) middleware.Responder
}

// NewAddProxyUser creates a new http.Handler for the add proxy user operation
func NewAddProxyUser(ctx *middleware.Context, handler AddProxyUserHandler) *AddProxyUser {
	return &AddProxyUser{Context: ctx, Handler: handler}
}

/*AddProxyUser swagger:route POST /cc/v1/proxyUser proxyUser addProxyUser

add proxyUser to User .

Optional extended description in Markdown.

*/
type AddProxyUser struct {
	Context *middleware.Context
	Handler AddProxyUserHandler
}

func (o *AddProxyUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddProxyUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
