// Code generated by go-swagger; DO NOT EDIT.

package proxy_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteProxyUserHandlerFunc turns a function with the right signature into a delete proxy user handler
type DeleteProxyUserHandlerFunc func(DeleteProxyUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteProxyUserHandlerFunc) Handle(params DeleteProxyUserParams) middleware.Responder {
	return fn(params)
}

// DeleteProxyUserHandler interface for that can handle valid delete proxy user params
type DeleteProxyUserHandler interface {
	Handle(DeleteProxyUserParams) middleware.Responder
}

// NewDeleteProxyUser creates a new http.Handler for the delete proxy user operation
func NewDeleteProxyUser(ctx *middleware.Context, handler DeleteProxyUserHandler) *DeleteProxyUser {
	return &DeleteProxyUser{Context: ctx, Handler: handler}
}

/*DeleteProxyUser swagger:route DELETE /cc/v1/proxyUser/{id} proxyUser deleteProxyUser

delete ProxyUser.

Optional extended description in Markdown.

*/
type DeleteProxyUser struct {
	Context *middleware.Context
	Handler DeleteProxyUserHandler
}

func (o *DeleteProxyUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteProxyUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
