apiVersion: v1
kind: Service
metadata:
  name: aide
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: aide
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30784
