// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-mf/pkg/models"
)

// GetImageOKCode is the HTTP code returned for type GetImageOK
const GetImageOKCode int = 200

/*GetImageOK OK

swagger:response getImageOK
*/
type GetImageOK struct {

	/*
	  In: Body
	*/
	Payload *models.Image `json:"body,omitempty"`
}

// NewGetImageOK creates GetImageOK with default headers values
func NewGetImageOK() *GetImageOK {

	return &GetImageOK{}
}

// WithPayload adds the payload to the get image o k response
func (o *GetImageOK) WithPayload(payload *models.Image) *GetImageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image o k response
func (o *GetImageOK) SetPayload(payload *models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageUnauthorizedCode is the HTTP code returned for type GetImageUnauthorized
const GetImageUnauthorizedCode int = 401

/*GetImageUnauthorized Unauthorized

swagger:response getImageUnauthorized
*/
type GetImageUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetImageUnauthorized creates GetImageUnauthorized with default headers values
func NewGetImageUnauthorized() *GetImageUnauthorized {

	return &GetImageUnauthorized{}
}

// WithPayload adds the payload to the get image unauthorized response
func (o *GetImageUnauthorized) WithPayload(payload *models.Error) *GetImageUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image unauthorized response
func (o *GetImageUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageNotFoundCode is the HTTP code returned for type GetImageNotFound
const GetImageNotFoundCode int = 404

/*GetImageNotFound The Models cannot be found

swagger:response getImageNotFound
*/
type GetImageNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetImageNotFound creates GetImageNotFound with default headers values
func NewGetImageNotFound() *GetImageNotFound {

	return &GetImageNotFound{}
}

// WithPayload adds the payload to the get image not found response
func (o *GetImageNotFound) WithPayload(payload *models.Error) *GetImageNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image not found response
func (o *GetImageNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
