#FROM dev.sf.dockerhub.stgwebank/webank/mlss-di:nginx-1.10-auth-request
FROM nginx:latest
ADD output/css /var/www/html/css/
ADD output/fonts /var/www/html/fonts/
ADD output/img /var/www/html/img/
ADD output/index.html /var/www/html/
ADD output/js /var/www/html/js/
ADD output/static /var/www/html/static/
ADD output/_book /var/www/html/_book