{{- $gpuCount := .Values.gpuCount -}}
{{- $gpuMemory := .Values.gpuMemory -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "custom-serving.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "custom-serving.chart" . }}
    app: {{ template "custom-serving.name" . }}
    servingName: "{{ .Values.servingName }}"
    servingType: "custom-serving"
    serviceName: "{{ .Values.servingName }}"
    servingVersion: "{{ .Values.servingVersion }}"
  annotations:
    "helm.sh/created": {{ .Release.Time.Seconds | quote }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
      app: {{ template "custom-serving.name" . }} 
  template:
    metadata:
      {{- if eq .Values.enableIstio true }}
      annotations:
        sidecar.istio.io/inject: "true"
      {{- end }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "custom-serving.chart" . }}
        app: {{ template "custom-serving.name" . }}
        serviceName: "{{ .Values.servingName }}"
        servingVersion: "{{ .Values.servingVersion }}"
    spec:
      containers:
        - name: custom-serving
          {{- if .Values.image }}
          image: "{{ .Values.image }}"
          {{- end }}
          {{- if .Values.imagePullPolicy }}
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          {{- end }}
          env:
          {{- if .Values.envs }}
          {{- range $key, $value := .Values.envs }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          {{- end }}
          {{- if ne .Values.command "" }}
          command:
          - "sh"
          - "-c"
          - "{{ .Values.command }}"
          {{- end }}
          ports:
            {{- if ne (int .Values.port) 0 }} 
            - containerPort: {{ .Values.port }}
              name: grpc
              protocol: TCP
            {{- end }}
            {{- if ne (int .Values.restApiPort) 0 }} 
            - containerPort: {{ .Values.restApiPort }}
              name: restful
              protocol: TCP
            {{- end }}
          #readinessProbe:
          #  tcpSocket:
          #    port: grpc
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
          resources:
            limits:
              {{- if .Values.cpu }}
              cpu: {{ .Values.cpu }}
              {{- end }}
              {{- if .Values.memory }}
              memory: {{ .Values.memory }}
              {{- end }}
              {{- if gt (int $gpuCount) 0}}
              nvidia.com/gpu: {{ .Values.gpuCount }}
              {{- end }}
              {{- if gt (int $gpuMemory) 0}}
              aliyun.com/gpu-mem: {{ .Values.gpuMemory }}
              {{- end }}
          volumeMounts:
            {{- if .Values.modelDirs }}
            {{- range $pvcName, $destPath := .Values.modelDirs}}
            - name: "{{ $pvcName }}"
              mountPath: "{{ $destPath }}"
            {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.modelDirs }}
        {{- range $pvcName, $destPath := .Values.modelDirs}}
        - name: "{{ $pvcName }}"
          persistentVolumeClaim:
            claimName: "{{ $pvcName }}"
        {{- end }}
        {{- end }}
