apiVersion: v1
kind: Service
metadata:
  name: bdap-ui-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: bdap-ui
  type: {{.Values.ui.service.bdap.type}}
  #type: ClusterIP
  ports:
  - protocol: TCP
    port: {{.Values.ui.service.bdap.port}}
    targetPort: {{.Values.ui.service.bdap.targetPort}}
    nodePort: {{.Values.ui.service.bdap.nodePort}}
  #externalTrafficPolicy: Local
