// Code generated by go-swagger; DO NOT EDIT.

package namespaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddNamespaceHandlerFunc turns a function with the right signature into a add namespace handler
type AddNamespaceHandlerFunc func(AddNamespaceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddNamespaceHandlerFunc) Handle(params AddNamespaceParams) middleware.Responder {
	return fn(params)
}

// AddNamespaceHandler interface for that can handle valid add namespace params
type AddNamespaceHandler interface {
	Handle(AddNamespaceParams) middleware.Responder
}

// NewAddNamespace creates a new http.Handler for the add namespace operation
func NewAddNamespace(ctx *middleware.Context, handler AddNamespaceHandler) *AddNamespace {
	return &AddNamespace{Context: ctx, Handler: handler}
}

/*AddNamespace swagger:route POST /cc/v1/namespaces Namespaces addNamespace

create a namespace.

Optional extended description in Markdown.

*/
type AddNamespace struct {
	Context *middleware.Context
	Handler AddNamespaceHandler
}

func (o *AddNamespace) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddNamespaceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
