// Code generated by go-swagger; DO NOT EDIT.

package namespaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// GetMyNamespaceOKCode is the HTTP code returned for type GetMyNamespaceOK
const GetMyNamespaceOKCode int = 200

/*GetMyNamespaceOK Detailed User and User information.

swagger:response getMyNamespaceOK
*/
type GetMyNamespaceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Namespace `json:"body,omitempty"`
}

// NewGetMyNamespaceOK creates GetMyNamespaceOK with default headers values
func NewGetMyNamespaceOK() *GetMyNamespaceOK {

	return &GetMyNamespaceOK{}
}

// WithPayload adds the payload to the get my namespace o k response
func (o *GetMyNamespaceOK) WithPayload(payload *models.Namespace) *GetMyNamespaceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get my namespace o k response
func (o *GetMyNamespaceOK) SetPayload(payload *models.Namespace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMyNamespaceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMyNamespaceUnauthorizedCode is the HTTP code returned for type GetMyNamespaceUnauthorized
const GetMyNamespaceUnauthorizedCode int = 401

/*GetMyNamespaceUnauthorized Unauthorized

swagger:response getMyNamespaceUnauthorized
*/
type GetMyNamespaceUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMyNamespaceUnauthorized creates GetMyNamespaceUnauthorized with default headers values
func NewGetMyNamespaceUnauthorized() *GetMyNamespaceUnauthorized {

	return &GetMyNamespaceUnauthorized{}
}

// WithPayload adds the payload to the get my namespace unauthorized response
func (o *GetMyNamespaceUnauthorized) WithPayload(payload *models.Error) *GetMyNamespaceUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get my namespace unauthorized response
func (o *GetMyNamespaceUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMyNamespaceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMyNamespaceNotFoundCode is the HTTP code returned for type GetMyNamespaceNotFound
const GetMyNamespaceNotFoundCode int = 404

/*GetMyNamespaceNotFound url to get myUsers not found.

swagger:response getMyNamespaceNotFound
*/
type GetMyNamespaceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMyNamespaceNotFound creates GetMyNamespaceNotFound with default headers values
func NewGetMyNamespaceNotFound() *GetMyNamespaceNotFound {

	return &GetMyNamespaceNotFound{}
}

// WithPayload adds the payload to the get my namespace not found response
func (o *GetMyNamespaceNotFound) WithPayload(payload *models.Error) *GetMyNamespaceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get my namespace not found response
func (o *GetMyNamespaceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMyNamespaceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
