// Code generated by go-swagger; DO NOT EDIT.

package restmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ProcessLine 加工线类型的全局变量的值类型
// swagger:model ProcessLine
type ProcessLine struct {

	// 类似GPU节点的 参数设置-任务执行设置-高级参数配置-模型用户组/加工线用户组
	GroupID string `json:"group_id,omitempty"`

	// 类似GPU节点的 参数设置-任务执行设置-高级参数配置-加工线名称
	ProcesslineID string `json:"processline_id,omitempty"`

	// 类似GPU节点的 参数设置-任务执行设置-高级参数配置-加工线版本
	ProcesslineVersionID string `json:"processline_version_id,omitempty"`
}

// Validate validates this process line
func (m *ProcessLine) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProcessLine) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessLine) UnmarshalBinary(b []byte) error {
	var res ProcessLine
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
