// Code generated by go-swagger; DO NOT EDIT.

package restmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RunConfig run config
// swagger:model RunConfig
type RunConfig struct {

	// global variables
	GlobalVariables []*GlobalVariable `json:"global_variables"`

	// wtss variables
	WtssVariables *WTSSVariables `json:"wtss_variables,omitempty"`
}

// Validate validates this run config
func (m *RunConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGlobalVariables(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWtssVariables(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RunConfig) validateGlobalVariables(formats strfmt.Registry) error {

	if swag.IsZero(m.GlobalVariables) { // not required
		return nil
	}

	for i := 0; i < len(m.GlobalVariables); i++ {
		if swag.IsZero(m.GlobalVariables[i]) { // not required
			continue
		}

		if m.GlobalVariables[i] != nil {
			if err := m.GlobalVariables[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("global_variables" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RunConfig) validateWtssVariables(formats strfmt.Registry) error {

	if swag.IsZero(m.WtssVariables) { // not required
		return nil
	}

	if m.WtssVariables != nil {
		if err := m.WtssVariables.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wtss_variables")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RunConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunConfig) UnmarshalBinary(b []byte) error {
	var res RunConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
