---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aide-web-app-cluster-role-{{.Values.namespace}}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - pods
  - nodes
  - nodes/status
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aide-web-app-binding-{{.Values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aide-web-app-cluster-role-{{.Values.namespace}}
subjects:
- kind: ServiceAccount
  name: aide-web-app
  namespace: {{.Values.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aide-web-app
  namespace: {{.Values.namespace}}

