apiVersion: v1
kind: Service
metadata:
  name: aide
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: aide
  type: {{.Values.aide.service.type}}
  ports:
  - protocol: TCP
    port: {{.Values.aide.service.port}}
    targetPort: {{.Values.aide.service.targetPort}}
    nodePort: {{.Values.aide.service.nodePort}}
