apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook-entrypoint-files
  namespace: {{.Values.namespace}}
data:
  start-sh: |
    #!/bin/bash
    # Copyright (c) Jupyter Development Team.
    # Distributed under the terms of the Modified BSD License.

    set -e

    #export NB_USER=$AIDE_USER
    # Handle special flags if we're root
    if [ $(id -u) == 0 ] ; then

        # Handle username change. Since this is cheap, do this unconditionally
        echo "Set username to: $NB_USER"
        usermod -d /home/$NB_USER -l $NB_USER jovyan

        # handle home and working directory if the username changed
        if [[ "$NB_USER" != "jovyan" ]]; then
            # changing username, make sure homedir exists
            # (it could be mounted, and we shouldn't create it if it already exists)
            if [[ ! -e "/home/$NB_USER" ]]; then
                echo "Relocating home dir to /home/$NB_USER"
                cp -r /home/jovyan "/home/$NB_USER"
            fi
            # if workdir is in /home/jovyan, cd to /home/$NB_USER
            if [[ "$PWD/" == "/home/jovyan/"* ]]; then
                newcwd="/home/$NB_USER/${PWD:13}"
                echo "Setting CWD to $newcwd"
                cd "$newcwd"
            fi
        fi

        # Change UID of NB_USER to NB_UID if it does not match
        if [ "$NB_UID" != $(id -u $NB_USER) ] ; then
            echo "Set $NB_USER UID to: $NB_UID"
            usermod -u $NB_UID $NB_USER
        fi

        # Change GID of NB_USER to NB_GID if NB_GID is passed as a parameter
        if [ "$NB_GID" ] ; then
            echo "Set $NB_USER GID to: $NB_GID"
            groupmod -g $NB_GID -o $(id -g -n $NB_USER)
        fi

        # Enable sudo if requested
        if [[ "$GRANT_SUDO" == "1" || "$GRANT_SUDO" == 'yes' ]]; then
            echo "Granting $NB_USER sudo access"
            echo "$NB_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/notebook
        fi

        chown -R $NB_USER:users /home/$NB_USER

        # ln work dir
        if [ -d /workspace ]
        then
           ln -s /workspace /home/$NB_USER/
           chown -h $NB_USER:users /home/$NB_USER/workspace
        fi

        # ln juypter config
        #if [ -d /.jupyter ]
        #then
        #   mv /home/$NB_USER/.jupyter /home/$NB_USER/.jupyter-bak
        #   ln -s /.jupyter /home/$NB_USER/
        #   chown -h $NB_USER:users /home/$NB_USER/.jupyter
        #fi

        # ln data dir
        name=$(ls / | grep data- | awk '/^d/ {print $NF}')
        for i in $name
        do
          ln -s "/$i" "/home/$NB_USER/$i"
          chown -h $NB_USER:users /home/$NB_USER/$i
        done

        # Source BDP ENV & Host & Set Yarn Resouces
        if [ -d /appcom ]
        then
            sh /appcom/config/MLSS-config/MLSS_AIDE-config/HOST_ENV.sh
            source /appcom/config/MLSS-config/MLSS_AIDE-config/Notebook_ENV.sh
            if [ ! -d /workspace/tmp ]
            then
               mkdir -p /workspace/tmp
               chown $NB_USER:users /workspace/tmp
            fi
            if [ ! -d /workspace/logs ]
            then 
               mkdir -p /workspace/logs
               chown $NB_USER:users /workspace/logs
            fi
            ln -s /workspace/tmp /appcom
            ln -s /workspace/logs /appcom

            if  [ -d /home/$NB_USER/.sparkmagic ]
            then
               rm -rf  /home/$NB_USER/.sparkmagic
            fi
            
            mkdir -p /home/$NB_USER/.sparkmagic            
            chown -R $NB_USER:users /home/$NB_USER/.sparkmagic
            chmod -R 755 /home/$NB_USER/.sparkmagic
            ln -s /etc/sparkmagic/config.json /home/$NB_USER/.sparkmagic/config.json            
            readonly HADOOP_USER_NAME=$NB_USER
        fi

        if [ ! -d /workspace/.mlss_var ]
        then
           mkdir /workspace/.mlss_var
           chown $NB_USER:users /workspace/.mlss_var
        fi
        
        if [ -e /opt/conda/bin/pipeline ]
        then
          echo "init fate pipeline"
          pipeline init --port 9380 --ip 127.0.0.1 --system-user guest
        fi


        echo "Execute the command: $*"
        if [ ! -e /bin/gosu ]
        then
           echo "Execute su"
           exec su $NB_USER -c "env PATH=$PATH $*"
        fi

        # Exec the command as NB_USER
        echo "Execute gosu"
        exec gosu $NB_USER /bin/sh -c "env PATH=$PATH $*"

    else
      if [[ ! -z "$NB_UID" && "$NB_UID" != "$(id -u)" ]]; then
          echo 'Container must be run as root to set $NB_UID'
      fi
      if [[ ! -z "$NB_GID" && "$NB_GID" != "$(id -g)" ]]; then
          echo 'Container must be run as root to set $NB_GID'
      fi
      if [[ "$GRANT_SUDO" == "1" || "$GRANT_SUDO" == 'yes' ]]; then
          echo 'Container must be run as root to grant sudo permissions'
      fi
        # Exec the command
        echo "Execute the command: $*"
        exec $*
    fi
