// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPipelineProcessLineNodeManifestHandlerFunc turns a function with the right signature into a get pipeline process line node manifest handler
type GetPipelineProcessLineNodeManifestHandlerFunc func(GetPipelineProcessLineNodeManifestParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPipelineProcessLineNodeManifestHandlerFunc) Handle(params GetPipelineProcessLineNodeManifestParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetPipelineProcessLineNodeManifestHandler interface for that can handle valid get pipeline process line node manifest params
type GetPipelineProcessLineNodeManifestHandler interface {
	Handle(GetPipelineProcessLineNodeManifestParams, interface{}) middleware.Responder
}

// NewGetPipelineProcessLineNodeManifest creates a new http.Handler for the get pipeline process line node manifest operation
func NewGetPipelineProcessLineNodeManifest(ctx *middleware.Context, handler GetPipelineProcessLineNodeManifestHandler) *GetPipelineProcessLineNodeManifest {
	return &GetPipelineProcessLineNodeManifest{Context: ctx, Handler: handler}
}

/*GetPipelineProcessLineNodeManifest swagger:route GET /di/v2/pipeline/processline_node_manifest Pipeline getPipelineProcessLineNodeManifest

GetPipelineProcessLineNodeManifest

获取可视化编辑/工作流中的加工线节点的描述数据结构

*/
type GetPipelineProcessLineNodeManifest struct {
	Context *middleware.Context
	Handler GetPipelineProcessLineNodeManifestHandler
}

func (o *GetPipelineProcessLineNodeManifest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPipelineProcessLineNodeManifestParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
