namespace: prophecis
#env: dev
envir: prophecis
platformNodeSelectors:
  mlss-node-role: platform
ceph_path: /data/bdap-ss/mlss-data
db:
  server: 127.0.0.1
  port: 3306
  name: prophecis_db
  user: prophecis
  pwd: prophecis@wedatasphere
image:
  registry: wedatasphere/prophecis
  pullPolicy: Always
gateway:
  address: 127.0.0.1
  port: 30778
ldap:
  address: ldap://127.0.0.1:1389/
  baseDN: dc=webank,dc=com
linkis:
  address: 127.0.0.1:8088
  tokenCode: BML-AUTH
linkispro:
  address: 127.0.0.1:8088
  tokenCode: BML-AUTH

  

#persistent
minio:
  server: 127.0.0.1
  port: 32001
  keyid: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  accesskey: AKIAIOSFODNN7EXAMPLE
mongo:
  address: mongo.prophecis.svc.cluster.local
  username: mlssopr
  password: mlssopr
  database: mlsstest
  authenticationDatabase: admin
etcd:
  address: http://etcd.prophecis.svc.cluster.local:2379
  username: test
  password: test
  prefix: test
objectstore:
  type: s3_datastore
  username: AKIAIOSFODNN7EXAMPLE
  password: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
elasticsearch:
  address: http://elasticsearch.prophecis.svc.cluster.local:9200
  host: elasticsearch.prophecis.svc.cluster.local
  port: "9200"
  username: test
  password: test
  scheme: http
persistent:
  etcd:
    path: /cosdata/prophecis/test/etcd
  localstack:
    path: /cosdata/prophecis/test/localstack
  mongo:
    path: /cosdata/prophecis/test/mongo



#mlflow service
trainer:
  version: trainer-v0.3.2
  replicas: 1
  cpus: 5000m
  memory: 2048Mi

storage:
  version: storage-v0.3.2
  replicas: 1
  cpus: 500m
  memory: 5000Mi
  uploadContainerPath: /uploaded-models
  share_storage_dir: /data/oss-storage
  storerServerEnvName: prophecis
  storerServerName: dlaas.ibm.com
  storerTls: true
  platformNamespace: prophecis
  storageCA: MIIFdTCCA12gAwIBAgIJAMpWS0cTdN/xMA0GCSqGSIb3DQEBCwUAMFExCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOWTEPMA0GA1UEBwwGQXJtb25rMQwwCgYDVQQKDANJQk0xFjAUBgNVBAMMDWRsYWFzLmlibS5jb20wHhcNMTkwODAxMDk0MDE1WhcNMjkwNzI5MDk0MDE1WjBRMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTlkxDzANBgNVBAcMBkFybW9uazEMMAoGA1UECgwDSUJNMRYwFAYDVQQDDA1kbGFhcy5pYm0uY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1qB+XOvdAPLBz7xIzsmK7wHvS9TMFmg70yC7+cvPQlXstSn7dSPHLJ/IRBrWkVIY0qbFioHAUWaAG59AVBHt2gd98FR8cMwaOAMr8mz20JHjyme01DvTuqri5UNXt1rIszI9h83lP/Ih+szrFcf2ZvsOROItQ2rcs/nY2/nt1A9SWO26x4Vy8UZKhml3OXFE1TzAc4cvjb8WrhwUUzNHEK0Lwq7KhQuMzSUALlBAwDzYKQPr8PXU8DKV4YO1Cs6hjYJirOCpCjq+jfRLnh3vcACbCazUSWLUzVbpSNWa5yA3emGccetT4VZBGl/2B9dp/Gh8H75pmcyzy6ziJAFXHWeV2lzdLDUDhuArHWIGskBUos/fW8QtkL5Suad0fMAsoRHE8sL0D+BiGF39i0Rjk6PKcLCxcLcJyU1felQMevjMFsDShHtY82NM0rsyLFAvWfv0cH+0LVO/Mo3I3xzt6Yg16UaQ9wU/qOjEw7mhqGw0fuB12HrLoBstof4Jyb3IMRkWM2TmlH918SKABuT69Dyrc4xX90arGI5ZqafiwVSLnzam73AmKgqJSUa2AwVIL5ZMX1Au7O9wi3U9p8gjb5+MOrjR4i2IPoz//9gwVj3pdu2tx2Ai9muH1Yi3tTh+IWMUB/LuOQSsdSd1kHt74mF5HzC8/3TJRyv4uNBfho0CAwEAAaNQME4wHQYDVR0OBBYEFHx/O0IFLMrFpYtbfUH6uojZHVNQMB8GA1UdIwQYMBaAFHx/O0IFLMrFpYtbfUH6uojZHVNQMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAKKYsj9Mjy819DOFKmE6eY+DIcBlkJGNzknZr0qp1eieDa/ZRADowbcw18iQDiXi01BNAygMSLf6132RVMNY9p92U2s4KWom1gfdBAykEnWuPB5uIXN7w5vV0X+Vp+kRI6op1UEhvf0fnpDKLjpfPx1wmUVZB2ARuXq2z18b67K7PkF5fgm07ngE1O+ByIC05xEpNE9UBCSlgDLfjUFtFGPeCfhIMlYeh2kgUY441U/ALneCv7WBR+09yUl51CEDENk4MCYq1qWqzYHuI9nlZzbU0G+JOVE0vPpgDkUOyZwbz244nI4jhI1cuFR00TMpXlQUe6rY3ndHImQD5NmS4kBr9xJm2e+H5cwY+/0GjNXOxx5olXcMiLl4R9VA+KMPS9kYKl7E/J0M2WUeXjEGcGHqg12/QKiI9fgIwd1WwkiJARDciUqYTw2GAOZrJ2lytH8WvV8lZIPUp8awUDnZzmg+iFIYlADCjtOu4bdlnFVTGURCvPvrYA+8evtdFhXimWB/Chfof/EYv3r4qImL2/+N192jxilFkb/OBMkmG9t97iLvJykjmTFKkzysRy53F4CVlgAAOst8MQsJ6tewmSvgHVWOT1Ohi3eNzMCW/fTEjsf9hO/j23DHjwzZ3JIQxwNmNpdk8yIyhEQNnBQGjsZxB3MANqyOiZcm1al/Tkxw

restapi:
  version: restapi-v0.3.2
  port: 30960
  replicas: 1
  cpus: 1000m
  memory: 2000Mi
#  mfserver:
#    url: http://127.0.0.1:30803

lcm:
  version: lcm-v0.3.2
  nodeport:
   start: 40000
   end: 50000
  replicas: 1
  cpus: 1000m
  memory: 1000Mi
  load_training_data_mem_in_mb: 300
  milli_cpu: 60
  mem_in_mb: 300
  device_plugin: true
  shared_volume_storage_class: ""
  mlssGroupId: 6002
  fluent_bit_log_path: /mlss/di/jobs/

jm:
  version: jobmonitor-v0.3.2

trainingdata:
  version: metrics-v0.3.2
  replicas: 1
  cpus: 50m
  memory: 64Mi

grafana:
  port: 3000
log:
  level: DEBUG

# Default RSA Creds for Horovod
rsapubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/we++xU+toNBQO/MYYQSE0LdEFlEcEoWil9lK2wLILTg7Hep7c8elgXEmIxb90xeFmZW9CJv3oVuverzYwQ0cmXbniZmiI48D48kaf8kmx2cTJID0udM8XlCgoXbljHUSAzCmom7eTuxEkitwi/3kH2MtDIWtKs8FVM68mVEoP2WyqfzbZyGdeQqEKb7TcYtl4LVBVAwEfG1MN/ndmanAzFQwt5okBeJXIMeSdjmGBd/q3DRj5wZpgt9vSa4214+PxuscjizGMaALx7YThwfmPUE5SniGzq+tqh++wUdq689UMPJO97+UwrlMBXkytxc0ci2S5BMumrBDmOGAxRbN root@fa485b34526a"
rsaprikey: "-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAv8HvvsVPraDQUDvzGGEEhNC3RBZRHBKFopfZStsCyC04Ox3q
e3PHpYFxJiMW/dMXhZmVvQib96Fbr3q82MENHJl254mZoiOPA+PJGn/JJsdnEySA
9LnTPF5QoKF25Yx1EgMwpqJu3k7sRJIrcIv95B9jLQyFrSrPBVTOvJlRKD9lsqn8
22chnXkKhCm+03GLZeC1QVQMBHxtTDf53ZmpwMxUMLeaJAXiVyDHknY5hgXf6tw0
Y+cGaYLfb0muNtePj8brHI4sxjGgC8e2E4cH5j1BOUp4hs6vraofvsFHauvPVDDy
Tve/lMK5TAV5MrcXNHItkuQTLpqwQ5jhgMUWzQIDAQABAoIBAQCAeOqrIX7UkR1/
4+pmtvlUEpH2aA1HhZFK8fl/EWS3wLQfx1dGBrgHxsWMC45n2Hm15MRRtebo7Y6D
7vN/NTgXpSnozmPEIZa7wG0H9/1IoegJBzfuvmEr3PSf6g3ClWwJ+WErA0DMaIwb
FONNsD0WDYFguTcGYdv5cmxgJ0gccdO6zdZh8LXrez7XctgOFXqk6BLGElgKecuR
8pNo9FhnSehIs/Oy1BVYA1Uwnug9Q/vqmF+bAZM1BLo/8oLHKHvOkObFy0vfjHyB
Kj1/YYR673+S/L+Bmih5cpAFABU9RV0HgPHBmnh4AVj4mgdHrnJAWOX9j5cqucPe
TtrrydTxAoGBAOuXhCracm2ljxiOXxG1fMdLDUvL3nedWGE5JozwvWMtB8Owj4gx
tPoQQGe8fOW2AMrtAZl7DlA+Qt4r4OvHyylSzGi53+JWiaYLcqaMA5eKO66XV1RX
92QGSEV0ZVMzchz4OdyiRsXDZywr1+fnctO832Yte6DgisflMyI1Q2vrAoGBANBe
WePqeq+PPX4VUAISYTTrlX7JFWmyS5am+9hevZ+S/BhtJewUXd+B5jKdoO8WB5gF
IOgVgBO4OpNGdbvS9kX3f+x7h4tG0XEeKvMpNQJxTH13LSCZ4H7Sz/3VwEsU0+oF
x9/nV/IVfg+29Q9uE1jcI/z5fYBmozbkSydRE3InAoGBAND3GeIw1KJw4RX04lqA
0earqWV7tR3/0G6cFJeayUF4pZRrvUQeYtoTJC1fQKE36EgWJP8P6Ug/kWwjG2PH
WWqT6H9Tr0PBYmKHcPBM7Lqzf/CCiJFlXSe5cs04Ss+bqDIN8rTCs2eixJanZOBr
qKwqsTSeTzQJNs/Leqly+RR1AoGAJKVTXdgxN4sTn4cUCSk+W1ZLdn7a+znWPWqk
xEr1QolROOKJVtnGILbxy1kZorLXJw9P2EFfwxgVhS1RK3VQxsFeiDK5he8wippp
p1ZJ8mIGt9Ir553oc6WT2uqq5QmGs5PMsT44o2TQROdCdjI/yNL+qVEfl2N1tQO1
i/agWuUCgYEAx1k2KKs3+rLHgUquOKYzy1VbSSy973rBPwrYa1ed0RO9Sg/KKMqQ
OJdIhe7lwxrspmUKaObVtpVEsP/Cf7dWT8lruDHsakXfcNCoKXCBMYgnj593TdKu
SOqZdzFqgInvqttvMiJY1cydGSebuQ8IATOsyEKtBsk/BOPwgZFttGs=
-----END RSA PRIVATE KEY-----"

cc:
  image:
    tag: cc-apiserver-v0.3.0
  containerPort:
    portHttp: 6666
    portHttps: 443
  service:
    type: NodePort
    port: 6666
    targetPort: 6666
    portHttps: 443
    targetPortHttps: 443
    nodePort: 30803
  subSystemId: 5265
  encodeFlag: true
  mlss:
    gid: 6002
    uid: 6002
  spec:
    volumes:
      hostPath:
        path: /appcom/log/controlcenter
      hostPath:
        mlssData: /data/bdap-ss/mlss-data
  admin:
    user: hadoop
    password: hadoop

ccGateway:
  image:
    tag: cc-apigateway-v0.3.0
  service:
    type: NodePort
    port: 8081
    targetPort: 8081
    nodePort: 30778
  deployNode: mlssdi010001

aide:
  image:
    tag: mllabis-v0.3.2
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30790
  startPort: "32768"
  endPort: "50000"
  maxSparkSessionNum: 3

ui:
  image:
    tag: ui-v0.3.0
  service:
    bdap:
      type: NodePort
      port: 80
      targetPort: 80
      nodePort: 30803
  config:
    bdap:
      uiServer: bdap-ui
      filterUiServer: true
  notebook:
    mlssToken: MLSSTOKEN
    env: SIT
    clusterName: 
      bdap: BDAP
  spec:
    volumes:
      hostPath:
        bdapPath: /appcom/log/ui-bdap
  diApiVersion: v1
  aideApiVersion: v1
  ccApiVersion: v1
  grafana:
    url: http://127.0.0.1:30780
  dashboard:
    url: http://127.0.0.1:30080
  prometheus:
    url: http://127.0.0.1:30778
  kibana:
    url: http://127.0.0.1:30783
  di:
    image:
      trainingTags:
      - name: MLSS-AIDE_1.15.0_tensorflow-1.12.0-notebook-gpu-v0.4.0-mlpipeline
    baseHDFSPath: hdfs:///tmp/linkis
    linkis:
      hdfsBaseDir: hdfs:///tmp/linkis
      pythonOption:
      - tensorflow-1.12.0: hdfs:///tmp/linkis/mlss/tf_env.zip
  aide:
    image:
      notebookTags:
      - name: MLSS-AIDE_1.8.0_tensorflow-2.0.0-jupyterlab-gpu-v0.5.0


mlflow:
  address: 127.0.0.1:31525
  port: 31525

tfjob:
  image:
    mpiOperator: wedatasphere/prophecis:mpi-operator-v1.0.0
    tfOperator: wedatasphere/prophecis:tf-operator-v1.0.0
    delivery: wedatasphere/prophecis:kubectl-delivery-1.0.0

mf:
  image:
    tag: mf-server-v0.3.0
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    portHttps: 443
    targetPortHttps: 443
    nodePort: 30803
  cpus: 1500m
  memory: 1500Mi
  containerEngineCpu: 1
  containerEngineMemory: 1
  containerEngineGpu: "0"
  istioSideCarCpu: 2
  istioSideCarMemory: 1
  istioSideCarGpu: 0 
  CCAddress: https://controlcenter-go

