// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetNotebookUserResponse get notebook user response
// swagger:model GetNotebookUserResponse
type GetNotebookUserResponse struct {

	// Proxy User of Notebook.
	ProxyUser string `json:"ProxyUser,omitempty"`

	// Create User of Notebook.
	User string `json:"User,omitempty"`
}

// Validate validates this get notebook user response
func (m *GetNotebookUserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetNotebookUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetNotebookUserResponse) UnmarshalBinary(b []byte) error {
	var res GetNotebookUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
