// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Group group
// swagger:model Group
type Group struct {

	// the clusterName of group
	ClusterName string `json:"clusterName,omitempty"`

	// the departmentId of group
	DepartmentID int64 `json:"departmentId,omitempty"`

	// the departmentId of group
	DepartmentName string `json:"departmentName,omitempty"`

	// Whether the data is valid
	EnableFlag int64 `json:"enableFlag,omitempty"`

	// the type of group
	GroupType string `json:"groupType,omitempty"`

	// the id of group
	ID int64 `json:"id,omitempty"`

	// the groupName
	Name string `json:"name,omitempty"`

	// the uid remarks user
	Remarks string `json:"remarks,omitempty"`

	// rmb dcn
	RmbDcn string `json:"rmb_dcn,omitempty"`

	// rmb idc
	RmbIdc string `json:"rmb_idc,omitempty"`

	// service id
	ServiceID int64 `json:"service_id,omitempty"`

	// the systemId of group
	SubsystemID int64 `json:"subsystemId,omitempty"`

	// the systemName of group
	SubsystemName string `json:"subsystemName,omitempty"`
}

// Validate validates this group
func (m *Group) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Group) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Group) UnmarshalBinary(b []byte) error {
	var res Group
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
