// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UserList user list
// swagger:model UserList
type UserList struct {

	// user list
	UserList []*User `json:"userList"`
}

// Validate validates this user list
func (m *UserList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserList) validateUserList(formats strfmt.Registry) error {

	if swag.IsZero(m.UserList) { // not required
		return nil
	}

	for i := 0; i < len(m.UserList); i++ {
		if swag.IsZero(m.UserList[i]) { // not required
			continue
		}

		if m.UserList[i] != nil {
			if err := m.UserList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("userList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserList) UnmarshalBinary(b []byte) error {
	var res UserList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
