// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserNotebookAddressResponse user notebook address response
// swagger:model UserNotebookAddressResponse
type UserNotebookAddressResponse struct {

	// the notebookAddress
	NotebookAddress string `json:"notebookAddress,omitempty"`
}

// Validate validates this user notebook address response
func (m *UserNotebookAddressResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserNotebookAddressResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserNotebookAddressResponse) UnmarshalBinary(b []byte) error {
	var res UserNotebookAddressResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
