apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlcenter-go-deployment
  namespace: {{.Values.namespace}}
  labels: 
    app: controlcenter-go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlcenter-go
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: controlcenter-go
    spec:
      serviceAccountName: cc-go-sa
      containers:
      - name: cc
        image: {{.Values.server_repository}}:{{.Values.cc.image.tag}}
        imagePullPolicy: Always
        ports:
        
        - containerPort: 6666
        - containerPort: 443
        command:
        - /bin/bash
        - -c
        - "./mlss-controlcenter-go --host=0.0.0.0 --scheme=http --port=6666 --scheme=https --tls-port=443 --tls-certificate=/etc/config/server.crt --tls-key=/etc/config/server.key"
        env:
        - name: UM_SA_PWD
          value: sa
        - name: UM_OTHER_PWD
          value: other
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: log-volume
          mountPath: /var/log/controlcenter
        - name: timezone-volume
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: hubsecret-go
      volumes:
      - name: config-volume
        configMap:
          name: cc-go-config
          items:
          - key: application-yml
            path: application.yml
          - key: logback-spring-xml
            path: logback-spring.xml
          - key: server-crt
            path: server.crt
          - key: server-key
            path: server.key
      - name: log-volume
        hostPath:
          path: /appcom/log/controlcenter/{{.Values.namespace}}
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      nodeSelector:
        {{range $key,$val := .Values.platformNodeSelectors}}
          {{$key}}: {{$val}}
        {{end}}
