apiVersion: v1
kind: Service
metadata:
  name: controlcenter-gateway
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: controlcenter-gateway
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30778
    name: main
#  externalTrafficPolicy: Local
