apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-gateway-config
  namespace: {{.Values.namespace}}
data:
  application-yml: |
    authAddress:
      user: http://controlcenter-go:6666/cc/v1/inter/user
      auth: http://controlcenter-go:6666/cc/v1/inter/auth
      ip: http://controlcenter-go:6666/cc/v1/inter/ip
    checkApi:
      userOrAuthApi: /userOrAuthInterceptor
      ipApi: /ipInterceptor
    noteBook:
      authUrl: /cc/v1/auth/access/namespaces/*/notebooks/*  
    
  Caddyfile: |
    :8081 {
      root /home
      auth_request {
        check {
          path /cc/v1/*
          api /userOrAuthInterceptor
          except GET /di/v1/dssUserInfo
          except GET /mf/v1/dashboard?clusterName=bdp
          except GET /cc/v1/groups/group/storage/bdap
          except GET /cc/v1/namespaces/myNamespace
          except GET /cc/v1/login /cc/v1/logout /cc/v1/auth/access/namespaces/*/notebooks/*
          except GET /cc/v1/auth/access/mlflow/uri/*
          except POST /cc/v1/alerts  /cc/v1/alerts/training
          except GET /cc/v1/inter/user
          except POST /cc/v1/LDAPlogin
          except GET /cc/v1/getrsapubkey

        }

        check {
          path /di/v1/*
          except GET /di/v1/dssUserInfo
        }

        check {
          path /mlflow/ajax-api/2.0/*
          api /userOrAuthInterceptor
        }

        #check {
        #  path /mf/v1/*
        #  except GET /mf/v1/dashboard?clusterName=bdp 
        #}

        #check {
          #path /notebook/*
          #api /ipInterceptor
        #}     
      }

      timeouts 5m

      errors error.log
      log access.log
      gzip
      #proxy /cc https://controlcenter-go {
      proxy /cc http://controlcenter-go:6666 {
        header_upstream MLSS-Token {MLSS-Token}
        header_upstream MLSS-RealIP {remote}
        header_upstream X-Real-IP {remote}
        header_upstream MLSS-Userid {MLSS-Userid}
        header_upstream MLSS-Auth-Type {MLSS-Auth-Type}
        header_upstream MLSS-UIURL {MLSS-UIURL}
        header_upstream MLSS-Passwd {MLSS-Passwd}
        header_upstream MLSS-APPID {MLSS-APPID}
        header_upstream MLSS-APPTimestamp {MLSS-APPTimestamp}
        header_upstream MLSS-APPSignature {MLSS-APPSignature}

        ca_certificates /caddy-config/server.crt
        #insecure_skip_verify

        transparent
        websocket
      }

      proxy /aide aide:8080 {
        header_upstream MLSS-Token {MLSS-Token}
        header_upstream MLSS-RealIP {remote}
        header_upstream X-Real-IP {remote}
        header_upstream MLSS-Userid {MLSS-Userid}
        header_upstream MLSS-Auth-Type {MLSS-Auth-Type}
        header_upstream MLSS-UIURL {MLSS-UIURL}
        header_upstream MLSS-Passwd {MLSS-Passwd}
        header_upstream MLSS-APPID {MLSS-APPID}
        header_upstream MLSS-APPTimestamp {MLSS-APPTimestamp}
        header_upstream MLSS-APPSignature {MLSS-APPSignature}

        transparent
        websocket
      }

      proxy /di {{.Values.gateway.address}}:30960 {
        header_upstream MLSS-Token {MLSS-Token}
        header_upstream MLSS-RealIP {remote}
        header_upstream X-Real-IP {remote}
        header_upstream MLSS-Userid {MLSS-Userid}
        header_upstream MLSS-Auth-Type {MLSS-Auth-Type}
        header_upstream MLSS-UIURL {MLSS-UIURL}
        header_upstream MLSS-Passwd {MLSS-Passwd}
        header_upstream MLSS-APPID {MLSS-APPID}
        header_upstream MLSS-APPTimestamp {MLSS-APPTimestamp}
        header_upstream MLSS-APPSignature {MLSS-APPSignature}
        # header_upstream Upgrade {>Upgrade}
        # header_upstream Connection {>Connection}
        transparent
        websocket
      }

      proxy /mf mf:8080 {
        header_upstream MLSS-Token {MLSS-Token}
        header_upstream MLSS-RealIP {remote}
        header_upstream X-Real-IP {remote}
        header_upstream MLSS-Userid {MLSS-Userid}
        header_upstream MLSS-Auth-Type {MLSS-Auth-Type}
        header_upstream MLSS-UIURL {MLSS-UIURL}
        header_upstream MLSS-Passwd {MLSS-Passwd}
        header_upstream MLSS-APPID {MLSS-APPID}
        header_upstream MLSS-APPTimestamp {MLSS-APPTimestamp}
        header_upstream MLSS-APPSignature {MLSS-APPSignature}
        transparent
        websocket
      }

    }

  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIICzDCCAbQCCQCVrtRO5rcr1DANBgkqhkiG9w0BAQUFADAoMQswCQYDVQQGEwJD
    TjEZMBcGA1UEAwwQY29udHJvbGNlbnRlci1nbzAeFw0yMDA1MDcxMDUyMzlaFw0z
    MDA1MDUxMDUyMzlaMCgxCzAJBgNVBAYTAkNOMRkwFwYDVQQDDBBjb250cm9sY2Vu
    dGVyLWdvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy7p22tSPDmN7
    a7tRndX7NiEDYv+6mhFwSw/liUCe4rECF6v457eqNlmd+qo1JHYxBMelakFZtSt/
    TpcAuz8vRQFmK61qwPruEqg5/S5VtQQNzrGkuOEthOD6+Joepfo1aSiBHl8ec6Fr
    vYJkRijaoL3g2w/91Vt1LncrfsaPZBCKZ2epgsCnLYVQogxu/0gKBng9ilsMcBVA
    GeAeAPmxW/4I+mO1a342L53A8xZU2RaDXbZsBLucH1ONIhLb7Zja1fUCJi7HRmIL
    LfUzgJ62v4tsvZtLRoaA2QA4mEZesIPHeJpgQRmgpD5BmLxX9SHekoLTWqDCAA3z
    XnxjHjgkawIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQAa3Q0ui/Jqy1h+2DG+yyDf
    wtyemM0C9AjZFHiX10bG6EzdRlxX8lk1SJf1oQTnBhMR30FoI3ZyN+N9/uNvLHy+
    9zarQT8GiaBJCV4otIZ6V27AeeKaWOFju3ZJUTZ3VlxPRn0qzeIQkNk2Z2HwEPXG
    /ppDXqqSpChC7jWRr34ZClwdCiWVN3RL18c02giCJn/FBdLmxyia72Wjhox/zN+N
    lnGyr00Jcoj26dwN8bxDmgrmkbJKeVgqUXgys9Hc2Vl1c9jv0NGbrI7YcAxCwHxj
    NW/H5Z/FuR0A0ifTo5UgziamPGj0sB/OmZE/TPOSTFsaiM2IudAjwE8S32ihgJzo
    -----END CERTIFICATE-----
