apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlcenter-gateway-deployment
  namespace: {{.Values.namespace}}
  labels: 
    app: controlcenter-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlcenter-gateway
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: controlcenter-gateway
    spec:
      #serviceAccountName: cc-go-sa
      containers:
      - name: cc-gateway
        image: {{.Values.image.registry}}:{{.Values.ccGateway.image.tag}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        ports:
        - containerPort: 8081
        command: ["/bin/sh", "-c"]
        args:
          #- /bin/sh /go/bin/dlv  --listen=:40005 --headless=true --api-version=2 exec  /apigateway/mlss-apigateway -conf /caddy-config/Caddyfile
          #- /go/bin/dlv  --listen=:40005 --headless=true --api-version=2 exec  /apigateway/mlss-apigateway --  -conf /caddy-config/Caddyfile
          -  /apigateway/mlss-apigateway  -conf /caddy-config/Caddyfile
        #args:
        #  - PATH="$PATH:/apigateway"
        volumeMounts:
        - name: config-volume
          mountPath: /caddy-config
        - name: timezone-volume
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: hubsecret
      volumes:
      - name: config-volume
        configMap:
          name: cc-gateway-config
          items:
          - key: Caddyfile
            path: Caddyfile
          - key: application-yml
            path: application.yml
          - key: server.crt
            path: server.crt
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      nodeSelector:
        {{range $key,$val := .Values.platformNodeSelectors}}
          {{$key}}: {{$val}}
        {{end}}
