// Code generated by go-swagger; DO NOT EDIT.

package logouts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// LogoutOKCode is the HTTP code returned for type LogoutOK
const LogoutOKCode int = 200

/*LogoutOK logout.

swagger:response logoutOK
*/
type LogoutOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewLogoutOK creates LogoutOK with default headers values
func NewLogoutOK() *LogoutOK {

	return &LogoutOK{}
}

// WithPayload adds the payload to the logout o k response
func (o *LogoutOK) WithPayload(payload *models.Result) *LogoutOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout o k response
func (o *LogoutOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogoutUnauthorizedCode is the HTTP code returned for type LogoutUnauthorized
const LogoutUnauthorizedCode int = 401

/*LogoutUnauthorized Unauthorized

swagger:response logoutUnauthorized
*/
type LogoutUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewLogoutUnauthorized creates LogoutUnauthorized with default headers values
func NewLogoutUnauthorized() *LogoutUnauthorized {

	return &LogoutUnauthorized{}
}

// WithPayload adds the payload to the logout unauthorized response
func (o *LogoutUnauthorized) WithPayload(payload *models.Error) *LogoutUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout unauthorized response
func (o *LogoutUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogoutNotFoundCode is the HTTP code returned for type LogoutNotFound
const LogoutNotFoundCode int = 404

/*LogoutNotFound the url to logout not found.

swagger:response logoutNotFound
*/
type LogoutNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewLogoutNotFound creates LogoutNotFound with default headers values
func NewLogoutNotFound() *LogoutNotFound {

	return &LogoutNotFound{}
}

// WithPayload adds the payload to the logout not found response
func (o *LogoutNotFound) WithPayload(payload *models.Error) *LogoutNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout not found response
func (o *LogoutNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
