// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddUserToGroupHandlerFunc turns a function with the right signature into a add user to group handler
type AddUserToGroupHandlerFunc func(AddUserToGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddUserToGroupHandlerFunc) Handle(params AddUserToGroupParams) middleware.Responder {
	return fn(params)
}

// AddUserToGroupHandler interface for that can handle valid add user to group params
type AddUserToGroupHandler interface {
	Handle(AddUserToGroupParams) middleware.Responder
}

// NewAddUserToGroup creates a new http.Handler for the add user to group operation
func NewAddUserToGroup(ctx *middleware.Context, handler AddUserToGroupHandler) *AddUserToGroup {
	return &AddUserToGroup{Context: ctx, Handler: handler}
}

/*AddUserToGroup swagger:route POST /cc/v1/groups/users Groups addUserToGroup

add user to group.

Optional extended description in Markdown.

*/
type AddUserToGroup struct {
	Context *middleware.Context
	Handler AddUserToGroupHandler
}

func (o *AddUserToGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddUserToGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
