// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteGroupByNameHandlerFunc turns a function with the right signature into a delete group by name handler
type DeleteGroupByNameHandlerFunc func(DeleteGroupByNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteGroupByNameHandlerFunc) Handle(params DeleteGroupByNameParams) middleware.Responder {
	return fn(params)
}

// DeleteGroupByNameHandler interface for that can handle valid delete group by name params
type DeleteGroupByNameHandler interface {
	Handle(DeleteGroupByNameParams) middleware.Responder
}

// NewDeleteGroupByName creates a new http.Handler for the delete group by name operation
func NewDeleteGroupByName(ctx *middleware.Context, handler DeleteGroupByNameHandler) *DeleteGroupByName {
	return &DeleteGroupByName{Context: ctx, Handler: handler}
}

/*DeleteGroupByName swagger:route DELETE /cc/v1/groups/name/{groupName} Groups deleteGroupByName

Returns a user.

Optional extended description in Markdown.

*/
type DeleteGroupByName struct {
	Context *middleware.Context
	Handler DeleteGroupByNameHandler
}

func (o *DeleteGroupByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteGroupByNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
