// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCurrentUserStoragePathHandlerFunc turns a function with the right signature into a get current user storage path handler
type GetCurrentUserStoragePathHandlerFunc func(GetCurrentUserStoragePathParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCurrentUserStoragePathHandlerFunc) Handle(params GetCurrentUserStoragePathParams) middleware.Responder {
	return fn(params)
}

// GetCurrentUserStoragePathHandler interface for that can handle valid get current user storage path params
type GetCurrentUserStoragePathHandler interface {
	Handle(GetCurrentUserStoragePathParams) middleware.Responder
}

// NewGetCurrentUserStoragePath creates a new http.Handler for the get current user storage path operation
func NewGetCurrentUserStoragePath(ctx *middleware.Context, handler GetCurrentUserStoragePathHandler) *GetCurrentUserStoragePath {
	return &GetCurrentUserStoragePath{Context: ctx, Handler: handler}
}

/*GetCurrentUserStoragePath swagger:route GET /cc/v1/groups/group/storage Groups getCurrentUserStoragePath

Returns a storage list.

Optional extended description in Markdown.

*/
type GetCurrentUserStoragePath struct {
	Context *middleware.Context
	Handler GetCurrentUserStoragePathHandler
}

func (o *GetCurrentUserStoragePath) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCurrentUserStoragePathParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
