// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetNamespacesByGroupIDHandlerFunc turns a function with the right signature into a get namespaces by group Id handler
type GetNamespacesByGroupIDHandlerFunc func(GetNamespacesByGroupIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNamespacesByGroupIDHandlerFunc) Handle(params GetNamespacesByGroupIDParams) middleware.Responder {
	return fn(params)
}

// GetNamespacesByGroupIDHandler interface for that can handle valid get namespaces by group Id params
type GetNamespacesByGroupIDHandler interface {
	Handle(GetNamespacesByGroupIDParams) middleware.Responder
}

// NewGetNamespacesByGroupID creates a new http.Handler for the get namespaces by group Id operation
func NewGetNamespacesByGroupID(ctx *middleware.Context, handler GetNamespacesByGroupIDHandler) *GetNamespacesByGroupID {
	return &GetNamespacesByGroupID{Context: ctx, Handler: handler}
}

/*GetNamespacesByGroupID swagger:route GET /cc/v1/groups/{groupId}/namespaces Groups getNamespacesByGroupId

get namespace by groupId.

Optional extended description in Markdown.

*/
type GetNamespacesByGroupID struct {
	Context *middleware.Context
	Handler GetNamespacesByGroupIDHandler
}

func (o *GetNamespacesByGroupID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetNamespacesByGroupIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
