// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserGroupsHandlerFunc turns a function with the right signature into a get user groups handler
type GetUserGroupsHandlerFunc func(GetUserGroupsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserGroupsHandlerFunc) Handle(params GetUserGroupsParams) middleware.Responder {
	return fn(params)
}

// GetUserGroupsHandler interface for that can handle valid get user groups params
type GetUserGroupsHandler interface {
	Handle(GetUserGroupsParams) middleware.Responder
}

// NewGetUserGroups creates a new http.Handler for the get user groups operation
func NewGetUserGroups(ctx *middleware.Context, handler GetUserGroupsHandler) *GetUserGroups {
	return &GetUserGroups{Context: ctx, Handler: handler}
}

/*GetUserGroups swagger:route GET /cc/v1/auth/access/usergroups/{userName} Groups getUserGroups

Returns userGroups.

Optional extended description in Markdown.

*/
type GetUserGroups struct {
	Context *middleware.Context
	Handler GetUserGroupsHandler
}

func (o *GetUserGroups) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserGroupsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
