// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateGroupHandlerFunc turns a function with the right signature into a update group handler
type UpdateGroupHandlerFunc func(UpdateGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateGroupHandlerFunc) Handle(params UpdateGroupParams) middleware.Responder {
	return fn(params)
}

// UpdateGroupHandler interface for that can handle valid update group params
type UpdateGroupHandler interface {
	Handle(UpdateGroupParams) middleware.Responder
}

// NewUpdateGroup creates a new http.Handler for the update group operation
func NewUpdateGroup(ctx *middleware.Context, handler UpdateGroupHandler) *UpdateGroup {
	return &UpdateGroup{Context: ctx, Handler: handler}
}

/*UpdateGroup swagger:route PUT /cc/v1/groups Groups updateGroup

Returns a list of groups.

Optional extended description in Markdown.

*/
type UpdateGroup struct {
	Context *middleware.Context
	Handler UpdateGroupHandler
}

func (o *UpdateGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
