// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	restmodels "webank/DI/restapi/api_v1/restmodels"
)

// GetJobLogByLineReader is a Reader for the GetJobLogByLine structure.
type GetJobLogByLineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJobLogByLineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetJobLogByLineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetJobLogByLineUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetJobLogByLineNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetJobLogByLineOK creates a GetJobLogByLineOK with default headers values
func NewGetJobLogByLineOK() *GetJobLogByLineOK {
	return &GetJobLogByLineOK{}
}

/*GetJobLogByLineOK handles this case with default header values.

OK
*/
type GetJobLogByLineOK struct {
	Payload *restmodels.LogResponse
}

func (o *GetJobLogByLineOK) Error() string {
	return fmt.Sprintf("[GET /di/v1/job/{training_id}/log][%d] getJobLogByLineOK  %+v", 200, o.Payload)
}

func (o *GetJobLogByLineOK) GetPayload() *restmodels.LogResponse {
	return o.Payload
}

func (o *GetJobLogByLineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.LogResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobLogByLineUnauthorized creates a GetJobLogByLineUnauthorized with default headers values
func NewGetJobLogByLineUnauthorized() *GetJobLogByLineUnauthorized {
	return &GetJobLogByLineUnauthorized{}
}

/*GetJobLogByLineUnauthorized handles this case with default header values.

Unauthorized
*/
type GetJobLogByLineUnauthorized struct {
	Payload *restmodels.Error
}

func (o *GetJobLogByLineUnauthorized) Error() string {
	return fmt.Sprintf("[GET /di/v1/job/{training_id}/log][%d] getJobLogByLineUnauthorized  %+v", 401, o.Payload)
}

func (o *GetJobLogByLineUnauthorized) GetPayload() *restmodels.Error {
	return o.Payload
}

func (o *GetJobLogByLineUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobLogByLineNotFound creates a GetJobLogByLineNotFound with default headers values
func NewGetJobLogByLineNotFound() *GetJobLogByLineNotFound {
	return &GetJobLogByLineNotFound{}
}

/*GetJobLogByLineNotFound handles this case with default header values.

Model create failed
*/
type GetJobLogByLineNotFound struct {
	Payload *restmodels.Error
}

func (o *GetJobLogByLineNotFound) Error() string {
	return fmt.Sprintf("[GET /di/v1/job/{training_id}/log][%d] getJobLogByLineNotFound  %+v", 404, o.Payload)
}

func (o *GetJobLogByLineNotFound) GetPayload() *restmodels.Error {
	return o.Payload
}

func (o *GetJobLogByLineNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
