// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi mlss-cc API
API description in Markdown.


    Schemes:
      https
    Host: gateway.mlss.cc
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
