// Code generated by go-swagger; DO NOT EDIT.

package auths

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// AdminUserCheckOKCode is the HTTP code returned for type AdminUserCheckOK
const AdminUserCheckOKCode int = 200

/*AdminUserCheckOK auth by adminUsername and username.

swagger:response adminUserCheckOK
*/
type AdminUserCheckOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewAdminUserCheckOK creates AdminUserCheckOK with default headers values
func NewAdminUserCheckOK() *AdminUserCheckOK {

	return &AdminUserCheckOK{}
}

// WithPayload adds the payload to the admin user check o k response
func (o *AdminUserCheckOK) WithPayload(payload *models.Result) *AdminUserCheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the admin user check o k response
func (o *AdminUserCheckOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AdminUserCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AdminUserCheckUnauthorizedCode is the HTTP code returned for type AdminUserCheckUnauthorized
const AdminUserCheckUnauthorizedCode int = 401

/*AdminUserCheckUnauthorized Unauthorized

swagger:response adminUserCheckUnauthorized
*/
type AdminUserCheckUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAdminUserCheckUnauthorized creates AdminUserCheckUnauthorized with default headers values
func NewAdminUserCheckUnauthorized() *AdminUserCheckUnauthorized {

	return &AdminUserCheckUnauthorized{}
}

// WithPayload adds the payload to the admin user check unauthorized response
func (o *AdminUserCheckUnauthorized) WithPayload(payload *models.Error) *AdminUserCheckUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the admin user check unauthorized response
func (o *AdminUserCheckUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AdminUserCheckUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AdminUserCheckNotFoundCode is the HTTP code returned for type AdminUserCheckNotFound
const AdminUserCheckNotFoundCode int = 404

/*AdminUserCheckNotFound url to add namespace not found.

swagger:response adminUserCheckNotFound
*/
type AdminUserCheckNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAdminUserCheckNotFound creates AdminUserCheckNotFound with default headers values
func NewAdminUserCheckNotFound() *AdminUserCheckNotFound {

	return &AdminUserCheckNotFound{}
}

// WithPayload adds the payload to the admin user check not found response
func (o *AdminUserCheckNotFound) WithPayload(payload *models.Error) *AdminUserCheckNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the admin user check not found response
func (o *AdminUserCheckNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AdminUserCheckNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
