// Code generated by go-swagger; DO NOT EDIT.

package auths

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// CheckResourceOKCode is the HTTP code returned for type CheckResourceOK
const CheckResourceOKCode int = 200

/*CheckResourceOK ok

swagger:response checkResourceOK
*/
type CheckResourceOK struct {
}

// NewCheckResourceOK creates CheckResourceOK with default headers values
func NewCheckResourceOK() *CheckResourceOK {

	return &CheckResourceOK{}
}

// WriteResponse to the client
func (o *CheckResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CheckResourceUnauthorizedCode is the HTTP code returned for type CheckResourceUnauthorized
const CheckResourceUnauthorizedCode int = 401

/*CheckResourceUnauthorized Unauthorized

swagger:response checkResourceUnauthorized
*/
type CheckResourceUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCheckResourceUnauthorized creates CheckResourceUnauthorized with default headers values
func NewCheckResourceUnauthorized() *CheckResourceUnauthorized {

	return &CheckResourceUnauthorized{}
}

// WithPayload adds the payload to the check resource unauthorized response
func (o *CheckResourceUnauthorized) WithPayload(payload *models.Error) *CheckResourceUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check resource unauthorized response
func (o *CheckResourceUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckResourceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CheckResourceNotFoundCode is the HTTP code returned for type CheckResourceNotFound
const CheckResourceNotFoundCode int = 404

/*CheckResourceNotFound url to add namespace not found.

swagger:response checkResourceNotFound
*/
type CheckResourceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCheckResourceNotFound creates CheckResourceNotFound with default headers values
func NewCheckResourceNotFound() *CheckResourceNotFound {

	return &CheckResourceNotFound{}
}

// WithPayload adds the payload to the check resource not found response
func (o *CheckResourceNotFound) WithPayload(payload *models.Error) *CheckResourceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check resource not found response
func (o *CheckResourceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
