// Code generated by go-swagger; DO NOT EDIT.

package auths

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserStorageCheckHandlerFunc turns a function with the right signature into a user storage check handler
type UserStorageCheckHandlerFunc func(UserStorageCheckParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserStorageCheckHandlerFunc) Handle(params UserStorageCheckParams) middleware.Responder {
	return fn(params)
}

// UserStorageCheckHandler interface for that can handle valid user storage check params
type UserStorageCheckHandler interface {
	Handle(UserStorageCheckParams) middleware.Responder
}

// NewUserStorageCheck creates a new http.Handler for the user storage check operation
func NewUserStorageCheck(ctx *middleware.Context, handler UserStorageCheckHandler) *UserStorageCheck {
	return &UserStorageCheck{Context: ctx, Handler: handler}
}

/*UserStorageCheck swagger:route GET /cc/v1/auth/access/users/{username}/storages Auths userStorageCheck

auth by username and path.

Optional extended description in Markdown.

*/
type UserStorageCheck struct {
	Context *middleware.Context
	Handler UserStorageCheckHandler
}

func (o *UserStorageCheck) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserStorageCheckParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
