// Code generated by go-swagger; DO NOT EDIT.

package model_storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetModelsHandlerFunc turns a function with the right signature into a get models handler
type GetModelsHandlerFunc func(GetModelsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetModelsHandlerFunc) Handle(params GetModelsParams) middleware.Responder {
	return fn(params)
}

// GetModelsHandler interface for that can handle valid get models params
type GetModelsHandler interface {
	Handle(GetModelsParams) middleware.Responder
}

// NewGetModels creates a new http.Handler for the get models operation
func NewGetModels(ctx *middleware.Context, handler GetModelsHandler) *GetModels {
	return &GetModels{Context: ctx, Handler: handler}
}

/*GetModels swagger:route GET /mf/v1/models modelStorage getModels

Get the list of Models

Get Models list.

*/
type GetModels struct {
	Context *middleware.Context
	Handler GetModelsHandler
}

func (o *GetModels) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetModelsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
