// Code generated by go-swagger; DO NOT EDIT.

package model_storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-mf/pkg/models"
)

// ListModelVersionPushEventsByModelVersionIDOKCode is the HTTP code returned for type ListModelVersionPushEventsByModelVersionIDOK
const ListModelVersionPushEventsByModelVersionIDOKCode int = 200

/*ListModelVersionPushEventsByModelVersionIDOK OK

swagger:response listModelVersionPushEventsByModelVersionIdOK
*/
type ListModelVersionPushEventsByModelVersionIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ModelVersionPushEventResp `json:"body,omitempty"`
}

// NewListModelVersionPushEventsByModelVersionIDOK creates ListModelVersionPushEventsByModelVersionIDOK with default headers values
func NewListModelVersionPushEventsByModelVersionIDOK() *ListModelVersionPushEventsByModelVersionIDOK {

	return &ListModelVersionPushEventsByModelVersionIDOK{}
}

// WithPayload adds the payload to the list model version push events by model version Id o k response
func (o *ListModelVersionPushEventsByModelVersionIDOK) WithPayload(payload *models.ModelVersionPushEventResp) *ListModelVersionPushEventsByModelVersionIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list model version push events by model version Id o k response
func (o *ListModelVersionPushEventsByModelVersionIDOK) SetPayload(payload *models.ModelVersionPushEventResp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListModelVersionPushEventsByModelVersionIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListModelVersionPushEventsByModelVersionIDUnauthorizedCode is the HTTP code returned for type ListModelVersionPushEventsByModelVersionIDUnauthorized
const ListModelVersionPushEventsByModelVersionIDUnauthorizedCode int = 401

/*ListModelVersionPushEventsByModelVersionIDUnauthorized Unauthorized

swagger:response listModelVersionPushEventsByModelVersionIdUnauthorized
*/
type ListModelVersionPushEventsByModelVersionIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListModelVersionPushEventsByModelVersionIDUnauthorized creates ListModelVersionPushEventsByModelVersionIDUnauthorized with default headers values
func NewListModelVersionPushEventsByModelVersionIDUnauthorized() *ListModelVersionPushEventsByModelVersionIDUnauthorized {

	return &ListModelVersionPushEventsByModelVersionIDUnauthorized{}
}

// WithPayload adds the payload to the list model version push events by model version Id unauthorized response
func (o *ListModelVersionPushEventsByModelVersionIDUnauthorized) WithPayload(payload *models.Error) *ListModelVersionPushEventsByModelVersionIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list model version push events by model version Id unauthorized response
func (o *ListModelVersionPushEventsByModelVersionIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListModelVersionPushEventsByModelVersionIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListModelVersionPushEventsByModelVersionIDNotFoundCode is the HTTP code returned for type ListModelVersionPushEventsByModelVersionIDNotFound
const ListModelVersionPushEventsByModelVersionIDNotFoundCode int = 404

/*ListModelVersionPushEventsByModelVersionIDNotFound Report push fail

swagger:response listModelVersionPushEventsByModelVersionIdNotFound
*/
type ListModelVersionPushEventsByModelVersionIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListModelVersionPushEventsByModelVersionIDNotFound creates ListModelVersionPushEventsByModelVersionIDNotFound with default headers values
func NewListModelVersionPushEventsByModelVersionIDNotFound() *ListModelVersionPushEventsByModelVersionIDNotFound {

	return &ListModelVersionPushEventsByModelVersionIDNotFound{}
}

// WithPayload adds the payload to the list model version push events by model version Id not found response
func (o *ListModelVersionPushEventsByModelVersionIDNotFound) WithPayload(payload *models.Error) *ListModelVersionPushEventsByModelVersionIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list model version push events by model version Id not found response
func (o *ListModelVersionPushEventsByModelVersionIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListModelVersionPushEventsByModelVersionIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
