// Code generated by go-swagger; DO NOT EDIT.

package model_storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListModelVersionPushEventsByModelVersionIDHandlerFunc turns a function with the right signature into a list model version push events by model version Id handler
type ListModelVersionPushEventsByModelVersionIDHandlerFunc func(ListModelVersionPushEventsByModelVersionIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListModelVersionPushEventsByModelVersionIDHandlerFunc) Handle(params ListModelVersionPushEventsByModelVersionIDParams) middleware.Responder {
	return fn(params)
}

// ListModelVersionPushEventsByModelVersionIDHandler interface for that can handle valid list model version push events by model version Id params
type ListModelVersionPushEventsByModelVersionIDHandler interface {
	Handle(ListModelVersionPushEventsByModelVersionIDParams) middleware.Responder
}

// NewListModelVersionPushEventsByModelVersionID creates a new http.Handler for the list model version push events by model version Id operation
func NewListModelVersionPushEventsByModelVersionID(ctx *middleware.Context, handler ListModelVersionPushEventsByModelVersionIDHandler) *ListModelVersionPushEventsByModelVersionID {
	return &ListModelVersionPushEventsByModelVersionID{Context: ctx, Handler: handler}
}

/*ListModelVersionPushEventsByModelVersionID swagger:route GET /mf/v1/modelVersion/push/{modelVersionId} modelStorage listModelVersionPushEventsByModelVersionId

get model version push events list

*/
type ListModelVersionPushEventsByModelVersionID struct {
	Context *middleware.Context
	Handler ListModelVersionPushEventsByModelVersionIDHandler
}

func (o *ListModelVersionPushEventsByModelVersionID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListModelVersionPushEventsByModelVersionIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
