// Code generated by go-swagger; DO NOT EDIT.

package storages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// AddStorageOKCode is the HTTP code returned for type AddStorageOK
const AddStorageOKCode int = 200

/*AddStorageOK Detailed Storage and Storage information.

swagger:response addStorageOK
*/
type AddStorageOK struct {

	/*
	  In: Body
	*/
	Payload *models.Storage `json:"body,omitempty"`
}

// NewAddStorageOK creates AddStorageOK with default headers values
func NewAddStorageOK() *AddStorageOK {

	return &AddStorageOK{}
}

// WithPayload adds the payload to the add storage o k response
func (o *AddStorageOK) WithPayload(payload *models.Storage) *AddStorageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add storage o k response
func (o *AddStorageOK) SetPayload(payload *models.Storage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddStorageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddStorageUnauthorizedCode is the HTTP code returned for type AddStorageUnauthorized
const AddStorageUnauthorizedCode int = 401

/*AddStorageUnauthorized Unauthorized

swagger:response addStorageUnauthorized
*/
type AddStorageUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddStorageUnauthorized creates AddStorageUnauthorized with default headers values
func NewAddStorageUnauthorized() *AddStorageUnauthorized {

	return &AddStorageUnauthorized{}
}

// WithPayload adds the payload to the add storage unauthorized response
func (o *AddStorageUnauthorized) WithPayload(payload *models.Error) *AddStorageUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add storage unauthorized response
func (o *AddStorageUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddStorageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddStorageNotFoundCode is the HTTP code returned for type AddStorageNotFound
const AddStorageNotFoundCode int = 404

/*AddStorageNotFound url to get allStorages not found.

swagger:response addStorageNotFound
*/
type AddStorageNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddStorageNotFound creates AddStorageNotFound with default headers values
func NewAddStorageNotFound() *AddStorageNotFound {

	return &AddStorageNotFound{}
}

// WithPayload adds the payload to the add storage not found response
func (o *AddStorageNotFound) WithPayload(payload *models.Error) *AddStorageNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add storage not found response
func (o *AddStorageNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddStorageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
