// Code generated by go-swagger; DO NOT EDIT.

package storages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mlss-controlcenter-go/pkg/models"
)

// GetAllStorageOKCode is the HTTP code returned for type GetAllStorageOK
const GetAllStorageOKCode int = 200

/*GetAllStorageOK Detailed Storage and Storage information.

swagger:response getAllStorageOK
*/
type GetAllStorageOK struct {

	/*
	  In: Body
	*/
	Payload *models.PageStorageList `json:"body,omitempty"`
}

// NewGetAllStorageOK creates GetAllStorageOK with default headers values
func NewGetAllStorageOK() *GetAllStorageOK {

	return &GetAllStorageOK{}
}

// WithPayload adds the payload to the get all storage o k response
func (o *GetAllStorageOK) WithPayload(payload *models.PageStorageList) *GetAllStorageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all storage o k response
func (o *GetAllStorageOK) SetPayload(payload *models.PageStorageList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllStorageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllStorageUnauthorizedCode is the HTTP code returned for type GetAllStorageUnauthorized
const GetAllStorageUnauthorizedCode int = 401

/*GetAllStorageUnauthorized Unauthorized

swagger:response getAllStorageUnauthorized
*/
type GetAllStorageUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllStorageUnauthorized creates GetAllStorageUnauthorized with default headers values
func NewGetAllStorageUnauthorized() *GetAllStorageUnauthorized {

	return &GetAllStorageUnauthorized{}
}

// WithPayload adds the payload to the get all storage unauthorized response
func (o *GetAllStorageUnauthorized) WithPayload(payload *models.Error) *GetAllStorageUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all storage unauthorized response
func (o *GetAllStorageUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllStorageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllStorageNotFoundCode is the HTTP code returned for type GetAllStorageNotFound
const GetAllStorageNotFoundCode int = 404

/*GetAllStorageNotFound url to get allStorages not found.

swagger:response getAllStorageNotFound
*/
type GetAllStorageNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllStorageNotFound creates GetAllStorageNotFound with default headers values
func NewGetAllStorageNotFound() *GetAllStorageNotFound {

	return &GetAllStorageNotFound{}
}

// WithPayload adds the payload to the get all storage not found response
func (o *GetAllStorageNotFound) WithPayload(payload *models.Error) *GetAllStorageNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all storage not found response
func (o *GetAllStorageNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllStorageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
