// Code generated by go-swagger; DO NOT EDIT.

package linkis_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	restmodels "webank/DI/restapi/api_v1/restmodels"
)

// GetLinkisJobStatusReader is a Reader for the GetLinkisJobStatus structure.
type GetLinkisJobStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLinkisJobStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLinkisJobStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetLinkisJobStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLinkisJobStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLinkisJobStatusOK creates a GetLinkisJobStatusOK with default headers values
func NewGetLinkisJobStatusOK() *GetLinkisJobStatusOK {
	return &GetLinkisJobStatusOK{}
}

/*GetLinkisJobStatusOK handles this case with default header values.

OK
*/
type GetLinkisJobStatusOK struct {
}

func (o *GetLinkisJobStatusOK) Error() string {
	return fmt.Sprintf("[GET /di/v1/experimentJob/{linkis_exec_id}/status][%d] getLinkisJobStatusOK ", 200)
}

func (o *GetLinkisJobStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLinkisJobStatusUnauthorized creates a GetLinkisJobStatusUnauthorized with default headers values
func NewGetLinkisJobStatusUnauthorized() *GetLinkisJobStatusUnauthorized {
	return &GetLinkisJobStatusUnauthorized{}
}

/*GetLinkisJobStatusUnauthorized handles this case with default header values.

Unauthorized
*/
type GetLinkisJobStatusUnauthorized struct {
	Payload *restmodels.Error
}

func (o *GetLinkisJobStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /di/v1/experimentJob/{linkis_exec_id}/status][%d] getLinkisJobStatusUnauthorized  %+v", 401, o.Payload)
}

func (o *GetLinkisJobStatusUnauthorized) GetPayload() *restmodels.Error {
	return o.Payload
}

func (o *GetLinkisJobStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLinkisJobStatusNotFound creates a GetLinkisJobStatusNotFound with default headers values
func NewGetLinkisJobStatusNotFound() *GetLinkisJobStatusNotFound {
	return &GetLinkisJobStatusNotFound{}
}

/*GetLinkisJobStatusNotFound handles this case with default header values.

Model create failed
*/
type GetLinkisJobStatusNotFound struct {
	Payload *restmodels.Error
}

func (o *GetLinkisJobStatusNotFound) Error() string {
	return fmt.Sprintf("[GET /di/v1/experimentJob/{linkis_exec_id}/status][%d] getLinkisJobStatusNotFound  %+v", 404, o.Payload)
}

func (o *GetLinkisJobStatusNotFound) GetPayload() *restmodels.Error {
	return o.Payload
}

func (o *GetLinkisJobStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
