// Code generated by go-swagger; DO NOT EDIT.

package dss_user_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	restmodels "webank/DI/restapi/api_v1/restmodels"
)

// GetDssUserInfoReader is a Reader for the GetDssUserInfo structure.
type GetDssUserInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDssUserInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDssUserInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetDssUserInfoUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDssUserInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDssUserInfoOK creates a GetDssUserInfoOK with default headers values
func NewGetDssUserInfoOK() *GetDssUserInfoOK {
	return &GetDssUserInfoOK{}
}

/*GetDssUserInfoOK handles this case with default header values.

OK
*/
type GetDssUserInfoOK struct {
	Payload *restmodels.DssUserInfo
}

func (o *GetDssUserInfoOK) Error() string {
	return fmt.Sprintf("[GET /di/v1/dssUserInfo][%d] getDssUserInfoOK  %+v", 200, o.Payload)
}

func (o *GetDssUserInfoOK) GetPayload() *restmodels.DssUserInfo {
	return o.Payload
}

func (o *GetDssUserInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.DssUserInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDssUserInfoUnauthorized creates a GetDssUserInfoUnauthorized with default headers values
func NewGetDssUserInfoUnauthorized() *GetDssUserInfoUnauthorized {
	return &GetDssUserInfoUnauthorized{}
}

/*GetDssUserInfoUnauthorized handles this case with default header values.

Unauthorized
*/
type GetDssUserInfoUnauthorized struct {
	Payload *restmodels.Error
}

func (o *GetDssUserInfoUnauthorized) Error() string {
	return fmt.Sprintf("[GET /di/v1/dssUserInfo][%d] getDssUserInfoUnauthorized  %+v", 401, o.Payload)
}

func (o *GetDssUserInfoUnauthorized) GetPayload() *restmodels.Error {
	return o.Payload
}

func (o *GetDssUserInfoUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDssUserInfoNotFound creates a GetDssUserInfoNotFound with default headers values
func NewGetDssUserInfoNotFound() *GetDssUserInfoNotFound {
	return &GetDssUserInfoNotFound{}
}

/*GetDssUserInfoNotFound handles this case with default header values.

Get UserInfo Not Found
*/
type GetDssUserInfoNotFound struct {
	Payload *restmodels.Error
}

func (o *GetDssUserInfoNotFound) Error() string {
	return fmt.Sprintf("[GET /di/v1/dssUserInfo][%d] getDssUserInfoNotFound  %+v", 404, o.Payload)
}

func (o *GetDssUserInfoNotFound) GetPayload() *restmodels.Error {
	return o.Payload
}

func (o *GetDssUserInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(restmodels.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
