apiVersion: v1
kind: Service
metadata:
  name: controlcenter-gateway
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: controlcenter-gateway
  type: {{.Values.cc.service.type}}
  ports:
  - protocol: TCP
    port: {{.Values.ccGateway.service.port}}
    targetPort: {{.Values.ccGateway.service.targetPort}}
    nodePort: {{.Values.ccGateway.service.nodePort}}
    name: main
#  externalTrafficPolicy: Local