apiVersion: v1
kind: Service
metadata:
  name: controlcenter-go
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: controlcenter-go
{{ if .Values.services.expose_node_port }}
  type: {{.Values.cc.service.type}}
{{ end }}
  ports:
  - protocol: TCP
    port: {{.Values.cc.service.port}}
    targetPort: {{.Values.cc.service.targetPort}}
{{ if .Values.services.expose_node_port }}
    nodePort: {{.Values.cc.service.nodePort}}
{{ end }}
    name: http
  - protocol: TCP
    port: {{.Values.cc.service.portHttps}}
    targetPort: {{.Values.cc.service.targetPortHttps}}
    name: https
#  externalTrafficPolicy: Local
