{{- if (not .Values.enableGangScheduler) -}}
{{- if .Values.useTensorboard }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tensorboard
  labels:
    app: {{ template "tfjob.name" . }}
    chart: {{ template "tfjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    createdBy: "TFJob"
    role: tensorboard
spec:
  template:
    metadata:
      labels:
        app: {{ template "tfjob.name" . }}
        chart: {{ template "tfjob.chart" . }}
        release: {{ .Release.Name }}
        role: tensorboard
    spec:
      {{- if ne (len .Values.tolerations) 0 }}
      tolerations:
      {{- range $tolerationKey := .Values.tolerations }}
        {{- if eq $tolerationKey "all" }}
        - operator: "Exists"
        {{- else }}
        - key: "{{ $tolerationKey }}"
          operator: "Exists"
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.ps }}
      {{- if .Values.hasGangScheduler }}
      {{- if .Values.enableGangScheduler }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- end }}
      {{- end }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: 
                  - {{ template "tfjob.name" . }}
              - key: release
                operator: In
                values: 
                  - {{ .Release.Name }}
              {{- if .Values.chief }}
              - key: tf-replica-type
                operator: In
                values: 
                  - "chief"
              {{- else }}
              - key: tf-replica-index
                operator: In
                values: 
                  - "0"
              - key: tf-replica-type
                operator: In
                values: 
                  - "worker"
              {{- end }}
            topologyKey: kubernetes.io/hostname
      {{- if .Values.enablePodSecurityContext }}
      {{- if .Values.isNonRoot}}
      securityContext:
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.podSecurityContext.runAsGroup }}
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        supplementalGroups:
          {{- range $group := .Values.podSecurityContext.supplementalGroups }}
          - {{ $group -}}
          {{ end }}
      {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.isLocalLogging }}
        - hostPath:
            path: "{{ .Values.hostLogPath }}"
          name: training-logs-volume
        {{- end }}
        {{- if (not .Values.isLocalLogging) }}
        {{- if .Values.dataset }}   
        {{- range $pvcName, $destPath := .Values.dataset }}
        - name: "{{ $pvcName }}"
          persistentVolumeClaim:
            claimName: "{{ $pvcName }}"
        {{- end }}
        {{- end }}
        {{- end }}
      containers:
      - name: tensorboard      
        {{- if .Values.isLocalLogging }}
        command: ["tensorboard", "--logdir", "/output/training_logs",  "--host",  "0.0.0.0"]
        {{- else}}
        command: ["tensorboard", "--logdir", "{{ .Values.trainingLogdir }}",  "--host",  "0.0.0.0"]
        {{- end }}
        image: "{{ .Values.tensorboardImage }}"
        imagePullPolicy: {{ .Values.tensorboardImagePullpolicy }}
        resources:
{{ toYaml .Values.tensorboardResources | indent 10 }}
        ports:
        - containerPort: 6006
        volumeMounts:
        {{- if .Values.isLocalLogging }}
        - mountPath: /output/training_logs
          name: training-logs-volume
        {{- else }}
        {{- if .Values.dataset }}   
        {{- range $pvcName, $destPath := .Values.dataset }}
        - name: "{{ $pvcName }}"
          mountPath: "{{ $destPath }}"
        {{- end }}
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}
