apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: di-jm
  namespace: {{.Values.namespace}}
  labels:
    service: di-jm
    environment: {{.Values.env}}
spec:
  selector:
    matchLabels:
      service: di-jm
      environment: {{.Values.env}}
  replicas: {{.Values.lcm.replicas}}
  template:
    metadata:
      labels:
        service: di-jm
        environment: {{.Values.env}}
        version:  {{.Values.lcm.version}}
    spec:
      volumes:
        - name: di-config
          configMap:
            name: di-config
        - name: ffdl-certs
          configMap:
            name: ffdl-certs
        - name: timezone-volume
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: File
      serviceAccount: {{.Values.docker.image_prefix}}lcm
      serviceAccountName: {{.Values.docker.image_prefix}}lcm
      containers:
      - name: jm
        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}{{.Values.docker.image_prefix}}:{{.Values.jm.version}}
{{ if .Values.docker.pullPolicy }}
        imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
        volumeMounts:
        - mountPath: /etc/mlss/
          name: di-config
        - mountPath: /etc/ssl/dlaas/
          name: ffdl-certs
        - name: timezone-volume
          mountPath: /etc/localtime
        env:
        - name: DLAAS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_LEARNER_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_LOAD_TRAINING_DATA_MEM_IN_MB
          value: "{{.Values.lcm.load_training_data_mem_in_mb}}"
        - name: DLAAS_MILLI_CPU
          value: "{{.Values.lcm.milli_cpu}}"
        - name: DLAAS_MEM_IN_MB
          value: "{{.Values.lcm.mem_in_mb}}"
        - name: DLAAS_DEVICE_PLUGIN
          value: "{{.Values.lcm.device_plugin}}"
        - name: DLAAS_IMAGE_TAG
          value: {{.Values.restapi.version}}
        - name: DLAAS_IMAGE_PULL_POLICY
          value: {{.Values.docker.pullPolicy}}
        - name: DLAAS_ENV
          value: {{.Values.env}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: DLAAS_IMAGE_PREFIX
          value: {{.Values.docker.image_prefix}}
        - name: DLAAS_LEARNER_TAG
          value: {{.Values.learner.tag}}
        - name: DLAAS_LEARNER_REGISTRY
          value: {{.Values.docker.registry}}/{{.Values.learner.docker_namespace}}
        - name: LINKIS_ADDRESS
          value: {{.Values.linkis.address}}
        - name: LINKIS_ADDRESS
          value: {{.Values.linkis.address}}
        - name: LINKIS_TOKEN_CODE
          value: {{.Values.linkis.tokenCode}}
        - name: ENVIR
          value: {{.Values.envir}}
        - name: DLAAS_PUSH_METRICS_ENABLED
          value: "true"
        - name: DLAAS_MONGO_ADDRESS
          value: mongo.$(DLAAS_POD_NAMESPACE).svc.cluster.local
        - name: DLAAS_MONGO_USERNAME
          value: {{.Values.mongo.username}}
        - name: DLAAS_MONGO_PASSWORD
          value: {{.Values.mongo.password}}
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8443 /main"]
        resources:
          limits:
            cpu: {{.Values.lcm.cpus}}
            memory: {{.Values.lcm.memory}}
      imagePullSecrets:
      - name: hubsecret
      nodeSelector:
       {{range $key,$val := .Values.platformNodeSelectors}}
         {{$key}}: {{$val}}
       {{end}}

