apiVersion: v1
kind: Secret
metadata:
  name: lcm-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
  DLAAS_ETCD_ADDRESS: {{.Values.etcd.address|b64enc}}
  DLAAS_ETCD_USERNAME: {{.Values.etcd.username|b64enc}}
  DLAAS_ETCD_PASSWORD: {{.Values.etcd.password|b64enc}}
  DLAAS_ETCD_PREFIX: {{.Values.etcd.prefix|b64enc}}
  #DLAAS_ETCD_CERT: {{.Values.etcd.cert}} #assumed to be already encoded
  DLAAS_LEARNER_TAG: {{.Values.learner.tag|b64enc}}
#### 1.4.1 #####
{{ if ne .Values.env "dev" }}
  DLAAS_MONGO_ADDRESS: {{.Values.mongo.address|b64enc}}
  DLAAS_MONGO_USERNAME: {{.Values.mongo.username|b64enc}}
  DLAAS_MONGO_PASSWORD: {{.Values.mongo.password|b64enc}}
{{ end }}
  DLAAS_OBJECTSTORE_TYPE: {{.Values.objectstore.type|b64enc}}
  # auth_url needs to be the FQDN due to a limitation in the local S3 mock
  DLAAS_OBJECTSTORE_AUTH_URL: {{printf "minio-%s:9000" .Values.envir |b64enc}}
  DLAAS_OBJECTSTORE_USER_NAME: {{.Values.objectstore.username|b64enc}}
  DLAAS_OBJECTSTORE_PASSWORD: {{.Values.objectstore.password|b64enc}}
#################

######1.5.1######
  FLUENT_ELASTICSEARCH_HOST: {{.Values.elasticsearch.host|b64enc}}
  FLUENT_ELASTICSEARCH_PORT: {{.Values.elasticsearch.port|b64enc}}
  FLUENT_ELASTICSEARCH_USER: {{.Values.elasticsearch.username|b64enc}}
  FLUENT_ELASTICSEARCH_PASSWD: {{.Values.elasticsearch.password|b64enc}}
#################
