apiVersion: v1
kind: Secret
metadata:
  name: storage-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
{{ if ne .Values.env "dev" }}
  DLAAS_MONGO_ADDRESS: {{"localhost:27017"|b64enc}}
  DLAAS_MONGO_USERNAME: {{"mlss"|b64enc}}
  DLAAS_MONGO_PASSWORD: {{"mlss"|b64enc}}
{{ end }}
  DLAAS_OBJECTSTORE_TYPE: {{"s3_datastore"|b64enc}}
  DLAAS_OBJECTSTORE_AUTH_URL: {{printf "minio-%v:9000" .Values.envir|b64enc}}
  DLAAS_OBJECTSTORE_USER_NAME: {{"AKIAIOSFODNN7EXAMPLE"|b64enc}}
  DLAAS_OBJECTSTORE_PASSWORD: {{"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"|b64enc}}

  DLAAS_ELASTICSEARCH_ADDRESS: {{"http://elasticsearch.prophecis.svc.cluster.local:9200"|b64enc}}
  DLAAS_ELASTICSEARCH_USERNAME: {{"test"|b64enc}}
  DLAAS_ELASTICSEARCH_PASSWORD: {{"test"|b64enc}}

