apiVersion: apps/v1
kind: Deployment
metadata:
  name: di-storage
  namespace: {{.Values.namespace}}
  labels:
    environment: {{.Values.env}}
    service: di-storage
spec:
  selector:
    matchLabels:
      service: di-storage
      environment: {{.Values.env}}
  replicas: {{.Values.storage.replicas}}
  template:
    metadata:
      labels:
        service: di-storage
        environment: {{.Values.env}}
        version: {{.Values.storage.version}}
    spec:
      volumes:
      - name: learner-config-volume
        configMap:
          name: learner-config
      - name: di-config
        configMap:
          name: di-config
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      - name: oss-storage
        hostPath:
          path: /data/bdap-ss/mlss-data/tmp
          type: Directory
      - name: ceph
        hostPath:
          path: {{.Values.ceph_host_path}}/{{.Values.envir}}{{.Values.storage.uploadHostPath}}
      containers:
      - name: di-storage-rpc-server
        image: {{.Values.docker.registry}}/{{.Values.docker.namespace}}{{.Values.docker.image_prefix}}:{{.Values.storage.version}}
{{ if .Values.docker.pullPolicy }}
        imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
        ports:
        - containerPort: 8443
        env:
        - name: DLAAS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DLAAS_ENV
          value: {{.Values.env}}
        - name: DLAAS_LOGLEVEL
          value: {{.Values.log.level}}
        - name: DLAAS_PUSH_METRICS_ENABLED
          value: "true"
        - name: LINKIS_ADDRESS
          value: {{.Values.linkis.address}}
        - name: LINKIS_TOKEN_CODE
          value: {{.Values.linkis.tokenCode}}
        - name: DLAAS_MONGO_ADDRESS
          value: mongo.$(DLAAS_POD_NAMESPACE).svc.cluster.local
        - name: DLAAS_MONGO_USERNAME
          value: {{.Values.mongo.username}}
        - name: DLAAS_MONGO_PASSWORD
          value: {{.Values.mongo.password}}
        - name: DLAAS_OBJECTSTORE_TYPE
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_TYPE
        - name: DLAAS_OBJECTSTORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_AUTH_URL
        - name: DLAAS_OBJECTSTORE_USER_NAME
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_USER_NAME
        - name: DLAAS_OBJECTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: DLAAS_OBJECTSTORE_PASSWORD
        - name: DLAAS_ELASTICSEARCH_SCHEME
          value: {{.Values.elasticsearch.scheme}}
{{ if eq .Values.env "dev" }}
        - name: DLAAS_ELASTICSEARCH_ADDRESS
          value: {{.Values.elasticsearch.address}}
{{ else }}
        - name: DLAAS_ELASTICSEARCH_ADDRESS
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_ADDRESS
        - name: DLAAS_ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_USERNAME
        - name: DLAAS_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trainingdata-secrets
              key: DLAAS_ELASTICSEARCH_PASSWORD
{{ end }}
        volumeMounts:
        - mountPath: /etc/learner-config
          name: learner-config-volume
        - mountPath: /etc/mlss/
          name: di-config
        - name: timezone-volume
          mountPath: /etc/localtime
        - name: ceph
          mountPath: {{.Values.storage.uploadContainerPath}}
          mountPath: {{.Values.storage.uploadContainerPath}}
        - name: oss-storage
          mountPath: /data/oss-storage
        command: ["/bin/sh", "-c"]
        args: ["DLAAS_PORT=8443 /main"]
        resources:
          limits:
            cpu: {{.Values.storage.cpus}}
            memory: {{.Values.storage.memory}}
      imagePullSecrets:
      - name: hubsecret
      nodeSelector:
       {{range $key,$val := .Values.platformNodeSelectors}}
         {{$key}}: {{$val}}
       {{end}}

